"""Cloud-side analysis of the LOCAL experiments (A1, F1, H1). Never re-runs them.

    python research/scripts/analyze_local.py                           # research/results/
    python research/scripts/analyze_local.py --root runs/smoke/research  # synthetic test

Produces (each only if its inputs exist):
  B1_failure_by_K    classes A / B / B-hub / R at every K, from A1
  D1_query_uncertainty   can label-free Stage-1 signals predict "no cover in the top 30"?
  E1_adaptive_k      adaptive-K policies vs fixed K at the same mean alignment budget
  F1s_stage1_summary paired coverage/recall deltas of Stage-1 variants (from F1)
  H1s_alignment_summary  paired deltas of alignment variants (from H1)

Leakage control (registered before any result exists, research/experiments/registry.yaml):
  * D1/E1 use WORK-DISJOINT 5-fold cross-fitting on the benchmark queries: the model and
    the policy thresholds are fit on 4 folds of works and evaluated on the held-out fold.
    No benchmark result selects anything that is then reported on the same queries.
  * The hub class uses a threshold fixed in advance: the 95th percentile of the
    label-free probe reference over the whole catalogue.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from itertools import product
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rrlib  # noqa: E402
import stats  # noqa: E402

SIGNALS = ["top1", "margin_1_2", "margin_1_10", "mean_top10", "std_top10", "mean_top100", "entropy_top100",
           "row_std", "z_top1", "query_kocc10", "top1_kocc10", "top1_hub_reference"]
MENUS = [(10, 30, 100), (10, 50, 200)]
BUDGETS = [10, 20, 30, 50, 100]
HUB_PCT = 95
N_FOLDS = 5


def read_csv(path: Path) -> list[dict]:
    with open(path) as fh:
        return list(csv.DictReader(fh))


def out_dir(root: Path, name: str) -> Path:
    d = root / name
    (d / "plots").mkdir(parents=True, exist_ok=True)
    return d


def finish(d: Path, exp: str, label: str, metrics: dict, sources: list[str], readme: str, per_query: list[dict] | None = None) -> None:
    import yaml

    rrlib.write_json(d / "metrics.json", {"experiment_id": exp, "evidence": label, "sources": sources, **metrics})
    (d / "config.yaml").write_text(yaml.safe_dump({"experiment_id": exp, "evidence": label, "script": "research/scripts/analyze_local.py",
                                                    "seed": stats.SEED, "n_folds": N_FOLDS, "menus": [list(m) for m in MENUS],
                                                    "budgets": BUDGETS, "hub_percentile": HUB_PCT, "signals": SIGNALS}, sort_keys=False))
    rrlib.write_json(d / "runtime.json", {"note": "cloud analysis of committed local outputs; nothing re-run", **rrlib.environment()})
    (d / "README.md").write_text(f"# {exp} ({label})\n\n{readme}\n\nGenerated by `research/scripts/analyze_local.py`; do not edit.\n")
    if per_query:
        with open(d / "per_query.csv", "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(per_query[0].keys()))
            w.writeheader()
            w.writerows(per_query)
    print(f"wrote {d}")


def a1_inputs(a1: Path):
    m = json.loads((a1 / "metrics.json").read_text())
    pq = read_csv(a1 / "per_query.csv")
    sig = read_csv(a1 / "signals.csv")
    cand = read_csv(a1 / "candidates.csv")
    ks = [e["K"] for e in m["by_k"]]
    return m, pq, sig, cand, ks


def col(rows, name, dtype=float):
    return np.array([dtype(r[name]) for r in rows])


# ---------------------------------------------------------------------------- B1
def b1(root: Path, a1: Path) -> None:
    m, pq, _, cand, ks = a1_inputs(a1)
    groups = [r["query_wid"] for r in pq]
    ref = {c["candidate_pid"]: float(c["hub_reference"]) for c in cand}
    thr = float(np.percentile(list(ref.values()), HUB_PCT))
    res = {}
    for k in ks:
        cov = col(pq, f"cov_K{k}", int)
        A = cov == 0
        for s in ("hyb", "hub"):
            first = col(pq, f"{s}_first_K{k}", int)
            top1_hub = np.array([ref[r[f"{s}_top1_K{k}"]] >= thr for r in pq])
            R = ~A & (first == 1)
            B = ~A & (first > 1)
            res[f"K{k}/{s}"] = {"A_no_cover": stats.boot_mean(A, groups), "B_hub_top1": stats.boot_mean(B & top1_hub, groups),
                                "B_other": stats.boot_mean(B & ~top1_hub, groups), "R_rank1": stats.boot_mean(R, groups),
                                "efficiency_R_given_covered": stats.boot_ratio(R, ~A, groups)}
    finish(out_dir(root, "B1_failure_by_K"), "B1", f"ANALYSIS of {m['evidence']}", {"hub_threshold": thr, "classes": res},
           [str(a1)], "Failure classes at every K. B_hub: a cover was in the shortlist but the rank-1 item is a hub "
                      f"(probe reference >= {HUB_PCT}th percentile of the catalogue, fixed in advance).")


# ---------------------------------------------------------------------------- D1 + E1
def standardise(x_train, x_test):
    mu, sd = x_train.mean(0), x_train.std(0) + 1e-12
    return (x_train - mu) / sd, (x_test - mu) / sd


def d1_e1(root: Path, a1: Path) -> None:
    m, pq, sig, _, ks = a1_inputs(a1)
    assert [r["query_pid"] for r in pq] == [r["query_pid"] for r in sig], "per_query.csv and signals.csv must align"
    groups = [r["query_wid"] for r in pq]
    x = np.column_stack([col(sig, s) for s in SIGNALS])
    k_target = 30 if 30 in ks else ks[len(ks) // 2]
    y = col(pq, f"cov_K{k_target}", int) == 0  # "no cover in the top 30"
    folds = stats.group_folds(groups, N_FOLDS)
    p_oof = np.zeros(len(pq))
    for f in range(N_FOLDS):
        tr, te = folds != f, folds == f
        xtr, xte = standardise(x[tr], x[te])
        p_oof[te] = stats.predict_logistic(xte, stats.fit_logistic(xtr, y[tr].astype(float)))
    uni = {s: {"auroc_for_no_cover": stats.auroc(x[:, j], y), "note": "AUROC < 0.5 means the signal is higher for coverable queries"} for j, s in enumerate(SIGNALS)}
    boot = []
    rng = np.random.default_rng(stats.SEED)
    uniq, inv = np.unique(groups, return_inverse=True)
    for _ in range(1000):
        pick = rng.integers(0, uniq.size, uniq.size)
        idx = np.concatenate([np.flatnonzero(inv == g) for g in pick])
        boot.append(stats.auroc(p_oof[idx], y[idx]))
    d1 = {"target": f"no cover in the top {k_target}", "base_rate": float(y.mean()),
          "cross_fitted_auroc": {"estimate": stats.auroc(p_oof, y), "ci_low": float(np.nanquantile(boot, 0.025)), "ci_high": float(np.nanquantile(boot, 0.975))},
          "univariate_auroc": uni}
    finish(out_dir(root, "D1_query_uncertainty"), "D1", f"ANALYSIS of {m['evidence']}", d1, [str(a1)],
           "Out-of-fold (work-disjoint, 5 folds) logistic regression on label-free Stage-1 signals, predicting whether Stage 1 "
           "misses every cover in its top 30. Univariate AUROCs are descriptive (no fitting).",
           [{"query_pid": r["query_pid"], "query_wid": r["query_wid"], "fold": int(folds[i]), "p_no_cover_oof": round(float(p_oof[i]), 6), "y_no_cover": int(y[i])} for i, r in enumerate(pq)])

    # ---- E1: adaptive K from the out-of-fold score ------------------------------------
    ap = {k: col(pq, f"hub_ap_K{k}") for k in ks}
    first = {k: col(pq, f"hub_first_K{k}", int) for k in ks}
    out = {"system": "hybrid + hub correction (alpha, lambda locked)", "menus": {}}
    for menu in MENUS:
        if not all(k in ks for k in menu):
            continue
        res_menu = {}
        for budget in BUDGETS:
            if budget not in ks:
                continue
            pol_ap, pol_first, pol_k = np.zeros(len(pq)), np.zeros(len(pq), int), np.zeros(len(pq), int)
            chosen = []
            for f in range(N_FOLDS):
                tr, te = folds != f, folds == f
                # refit the difficulty model inside the training folds only
                xtr, _ = standardise(x[tr], x[tr])
                inner = stats.group_folds(np.asarray(groups)[tr], N_FOLDS, seed=stats.SEED + 1)
                p_tr = np.zeros(tr.sum())
                for g in range(N_FOLDS):
                    a, b = inner != g, inner == g
                    xa, xb = standardise(x[tr][a], x[tr][b])
                    p_tr[b] = stats.predict_logistic(xb, stats.fit_logistic(xa, y[tr][a].astype(float)))
                xtr_all, xte = standardise(x[tr], x[te])
                p_te = stats.predict_logistic(xte, stats.fit_logistic(xtr_all, y[tr].astype(float)))
                best = None
                qs = np.quantile(p_tr, np.linspace(0, 1, 21))
                for order in ("more_k_when_uncertain", "less_k_when_uncertain"):
                    for t1, t2 in product(qs, qs):
                        if t2 < t1:
                            continue
                        tier = np.where(p_tr < t1, 0, np.where(p_tr < t2, 1, 2))
                        if order == "less_k_when_uncertain":
                            tier = 2 - tier
                        kk = np.array(menu)[tier]
                        if kk.mean() > budget + 1e-9:
                            continue
                        score = np.mean([ap[k][tr][i] for i, k in enumerate(kk)])
                        if best is None or score > best[0]:
                            best = (score, t1, t2, order)
                if best is None:  # budget below the smallest tier everywhere: fall back to the smallest K
                    best = (None, np.inf, np.inf, "more_k_when_uncertain")
                _, t1, t2, order = best
                tier = np.where(p_te < t1, 0, np.where(p_te < t2, 1, 2))
                if order == "less_k_when_uncertain":
                    tier = 2 - tier
                kk = np.array(menu)[tier]
                idx = np.flatnonzero(te)
                pol_k[idx] = kk
                pol_ap[idx] = [ap[k][i] for i, k in zip(idx, kk)]
                pol_first[idx] = [first[k][i] for i, k in zip(idx, kk)]
                chosen.append({"fold": f, "t1": float(t1), "t2": float(t2), "order": order})
            res_menu[f"budget{budget}"] = {
                "realised_mean_K": float(pol_k.mean()), "fixed_K": budget, "folds": chosen,
                "policy_MAP": float(pol_ap.mean()), "fixed_MAP": float(ap[budget].mean()),
                "delta_AP_policy_minus_fixed": stats.boot_delta(ap[budget], pol_ap, groups),
                "delta_Hit1_policy_minus_fixed": stats.boot_delta(first[budget] == 1, pol_first == 1, groups),
                "k_distribution": {str(k): float(np.mean(pol_k == k)) for k in menu},
            }
        out["menus"][str(menu)] = res_menu
    finish(out_dir(root, "E1_adaptive_k"), "E1", f"ANALYSIS of {m['evidence']}", out, [str(a1)],
           "Three-tier adaptive shortlist size chosen per query from the cross-fitted difficulty score. Thresholds are fit on "
           "training folds only, subject to mean K <= budget, and evaluated on the held-out works. Compared with fixed K = budget "
           "on the same queries (paired, work-level). A policy is only a contribution if it beats fixed K at equal or lower realised cost.")


# ---------------------------------------------------------------------------- F1 / H1 summaries
def f1(root: Path, f1dir: Path) -> None:
    m = json.loads((f1dir / "metrics.json").read_text())
    pq = read_csv(f1dir / "per_query.csv")
    groups = [r["query_wid"] for r in pq]
    variants = [c[: -len("_rel_ranks")] for c in pq[0] if c.endswith("_rel_ranks")]
    primary = [v for v in variants if v.startswith("global:")]
    if not primary:
        print("F1s skipped: no global:<checkpoint> variant to compare against (rerun F1 with the default --variants)")
        return
    base = primary[0]
    ranks = {v: [rrlib.str_to_ranks(r[f"{v}_rel_ranks"]) for r in pq] for v in variants}
    res = {}
    for k in (10, 30, 100, 500):
        for v in variants:
            cov = np.array([np.any(r <= k) for r in ranks[v]])
            rec = np.array([np.mean(r <= k) for r in ranks[v]])
            res.setdefault(v, {})[f"@{k}"] = {"coverage": stats.boot_mean(cov, groups), "recall": stats.boot_mean(rec, groups)}
    ref = m["notes"].get("primary", None)
    comps = {}
    ref_v = next((v for v in variants if v.startswith("global:") and ref and v.endswith(ref)), primary[-1])
    for v in variants:
        if v == ref_v:
            continue
        for k in (30, 100):
            a = np.array([np.any(r <= k) for r in ranks[ref_v]])
            b = np.array([np.any(r <= k) for r in ranks[v]])
            comps[f"{v} - {ref_v} @{k}"] = stats.boot_delta(a, b, groups)
    finish(out_dir(root, "F1s_stage1_summary"), "F1s", f"ANALYSIS of {m['evidence']}", {"reference": ref_v, "base": base, "curves": res, "paired_coverage": comps}, [str(f1dir)],
           "Stage-1 coverage and recall at fixed K for every Stage-1 variant, and paired work-level differences against the reference encoder.")


def h1(root: Path, h1dir: Path) -> None:
    m = json.loads((h1dir / "metrics.json").read_text())
    pq = read_csv(h1dir / "per_query.csv")
    groups = [r["query_wid"] for r in pq]
    variants = [c[: -len("_ap")] for c in pq[0] if c.endswith("_ap") and c != "s1_ap"]
    ref = next((v for v in variants if v == "profile_cosine_n384"), variants[0])
    comps = {f"{v} - {ref}": {"delta_AP": stats.boot_delta(col(pq, f"{ref}_ap"), col(pq, f"{v}_ap"), groups),
                              "delta_Hit1": stats.boot_delta(col(pq, f"{ref}_first", int) == 1, col(pq, f"{v}_first", int) == 1, groups)}
             for v in variants if v != ref}
    finish(out_dir(root, "H1s_alignment_summary"), "H1s", f"ANALYSIS of {m['evidence']}", {"reference": ref, "comparisons": comps}, [str(h1dir)],
           "Paired work-level differences between alignment variants on an identical K-candidate shortlist.")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--root", type=Path, default=rrlib.REPO / "research" / "results")
    p.add_argument("--a1", default="A1_k_sweep_long384")
    p.add_argument("--f1", default="F1_stage1_variants")
    p.add_argument("--h1", default="H1_alignment_ablation")
    p.add_argument("--menus", nargs="+", default=None, help="override menus, e.g. 5,10,30 (mechanics tests only)")
    p.add_argument("--budgets", nargs="+", type=int, default=None, help="override budgets (mechanics tests only)")
    args = p.parse_args(argv)
    global MENUS, BUDGETS
    if args.menus:
        MENUS = [tuple(int(x) for x in m.split(",")) for m in args.menus]
    if args.budgets:
        BUDGETS = args.budgets
    done = []
    if (args.root / args.a1 / "metrics.json").exists():
        b1(args.root, args.root / args.a1)
        d1_e1(args.root, args.root / args.a1)
        done += ["B1", "D1", "E1"]
    if (args.root / args.f1 / "metrics.json").exists():
        f1(args.root, args.root / args.f1)
        done.append("F1s")
    if (args.root / args.h1 / "metrics.json").exists():
        h1(args.root, args.root / args.h1)
        done.append("H1s")
    print("analysed:", ", ".join(done) if done else "nothing (no local results present yet)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
