"""ARTIFACT-ANALYSIS: everything that can be established from committed result files.

Runs in any environment with numpy (no Da-TACOS data, no checkpoints). Every output
is labelled ARTIFACT-ANALYSIS or ARTIFACT-REPRODUCTION (see research/ENVIRONMENT.md).

Key fact used throughout: the hybrid reranks only the first K = 30 Stage-1 candidates
and leaves the rest in Stage-1 order. Hence, per query,
  * a cover can reach hybrid rank 1 only if Stage 1 put at least one cover in its top 30;
  * if Stage 1's first cover is beyond 30, the hybrid's first cover rank equals Stage 1's.
The committed per-query files record, for every query and system, AP and the rank of
the FIRST relevant item, which is exactly what this decomposition needs.

    python research/scripts/artifact_analysis.py        # writes research/results/X*/
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rrlib  # noqa: E402
import stats  # noqa: E402

REPO = rrlib.REPO
RES = REPO / "reports" / "results"
OUT = REPO / "research" / "results"
K_LOCKED = 30
KS = [1, 5, 10, 20, 30, 50, 100, 200, 500, 1000, 2000, 5000, 14999]

RUNS = {
    "run1": ("benchmark.json", "benchmark_per_query.csv", "1,500-work encoder, 60 ep; 96-frame rerank"),
    "run2": ("benchmark_full96.json", "benchmark_per_query_full96.csv", "4,780-work encoder, 60 ep; 96-frame rerank; hub lambda 0.5"),
    "run3": ("benchmark_full384.json", "benchmark_per_query_full384.csv", "4,780-work encoder, 60 ep; 384-frame rerank; hub lambda 0.6"),
    "run4": ("benchmark_long384.json", "benchmark_per_query_long384.csv", "4,780-work encoder, 150 ep; 384-frame rerank; hub lambda 0.6"),
}


def load_run(run: str) -> tuple[dict, dict[str, np.ndarray], list[str]]:
    js, pq, _ = RUNS[run]
    meta = json.loads((RES / js).read_text())
    with open(RES / pq) as fh:
        rows = list(csv.DictReader(fh))
    cols = {}
    for c in rows[0]:
        if c.endswith("_ap"):
            cols[c] = np.array([float(r[c]) for r in rows])
        elif c.endswith("_first_rank"):
            cols[c] = np.array([int(r[c]) for r in rows])
    return meta, cols, [r["query_wid"] for r in rows]


def sys_key(cols: dict, prefix: str) -> str | None:
    hits = [c[: -len("_first_rank")] for c in cols if c.startswith(prefix) and c.endswith("_first_rank")]
    return hits[0] if hits else None


def save(exp: str, label: str, metrics: dict, sources: list[str], readme: str, per_query: list[dict] | None = None) -> None:
    d = OUT / exp
    (d / "plots").mkdir(parents=True, exist_ok=True)
    metrics = {"experiment_id": exp.split("_")[0], "evidence": label, "sources": sources, **metrics}
    rrlib.write_json(d / "metrics.json", metrics)
    import yaml

    (d / "config.yaml").write_text(yaml.safe_dump({"experiment_id": exp.split("_")[0], "evidence": label, "script": "research/scripts/artifact_analysis.py",
                                                    "seed": stats.SEED, "n_boot": stats.N_BOOT, "sources": sources}, sort_keys=False))
    rrlib.write_json(d / "runtime.json", {"note": "analysis of committed files; no model or alignment was run", **rrlib.environment()})
    (d / "README.md").write_text(f"# {exp} ({label})\n\n{readme}\n\nGenerated by `research/scripts/artifact_analysis.py`. Do not edit; regenerate.\n")
    if per_query:
        with open(d / "per_query.csv", "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(per_query[0].keys()))
            w.writeheader()
            w.writerows(per_query)


# ---------------------------------------------------------------------------- X0
def x0_reproduction() -> None:
    """Recompute every committed aggregate from the committed per-query file."""
    out = {}
    worst = 0.0
    for run in RUNS:
        meta, cols, _ = load_run(run)
        for m in meta["metrics"]:
            s = m["system"]
            first, ap = cols[f"{s}_first_rank"], cols[f"{s}_ap"]
            re = rrlib.summarize(first, ap)
            diffs = {k: abs(re[k] - m[k]) for k in ("MAP", "MRR", "Hit@1", "Hit@10", "mean_first_rank", "median_first_rank")}
            worst = max(worst, max(diffs.values()))
            out[f"{run}/{s}"] = {"max_abs_diff": max(diffs.values()), **{f"diff_{k}": v for k, v in diffs.items()}}
    save("X0_artifact_reproduction", "ARTIFACT-REPRODUCTION",
         {"systems": out, "max_abs_diff_overall": worst, "pass": worst < 1e-9},
         [f"reports/results/{v[0]}" for v in RUNS.values()] + [f"reports/results/{v[1]}" for v in RUNS.values()],
         "Every aggregate metric in the four benchmark JSONs recomputed from the per-query CSVs. "
         "This checks internal consistency of the committed artifacts; it does not re-run any model.")


# ---------------------------------------------------------------------------- X1
def x1_coverage() -> None:
    """Stage-1 query coverage C(K) = P(at least one cover in the top K), per encoder."""
    res = {}
    for run, enc in (("run1", "1,500 works, 60 ep"), ("run2", "4,780 works, 60 ep"), ("run4", "4,780 works, 150 ep")):
        meta, cols, groups = load_run(run)
        first = cols["global_embedding_first_rank"]
        res[run] = {"encoder": enc, "curve": {str(k): stats.boot_mean(first <= k, groups) for k in KS},
                    "shortlist_recall_K30_all_covers": meta["shortlist_recall"],
                    "quantiles_first_rank": {f"q{q}": float(np.quantile(first, q / 100)) for q in (10, 25, 50, 75, 90, 95, 99)}}
    # exhaustive classical alignment as a "Stage 1" (run 2 scored every pair, with and without correction)
    _, cols, groups = load_run("run2")
    for s in ("classical_alignment", "classical_alignment_hubcorr"):
        res[f"run2/{s}"] = {"curve": {str(k): stats.boot_mean(cols[f"{s}_first_rank"] <= k, groups) for k in KS}}
    # paired crossover test: learned Stage 1 (run 4) vs corrected exhaustive alignment (run 2), same 13,000 queries
    _, c4, g4 = load_run("run4")
    assert g4 == groups
    crossover = {str(k): stats.boot_delta(cols["classical_alignment_hubcorr_first_rank"] <= k, c4["global_embedding_first_rank"] <= k, groups)
                 for k in KS if k < 14999}
    save("X1_stage1_coverage", "ARTIFACT-ANALYSIS", {"K": KS, "coverage": res,
         "paired_embedding_minus_corrected_alignment": crossover},
         ["reports/results/benchmark_per_query*.csv", "reports/results/benchmark*.json"],
         "Share of the 13,000 benchmark queries with at least one true cover in the first K results, with work-level 95% intervals. "
         "This is the exact ceiling on Hit@1 for ANY reranker of a K-candidate shortlist. "
         "Shortlist recall over all 12 covers is only available at K = 30 (from the result JSONs); "
         "per-cover ranks were not committed, so recall at other K needs experiment A1.")


# ---------------------------------------------------------------------------- X2
def x2_failure_decomposition() -> None:
    """Classes at K = 30: A (no cover in shortlist), B (cover in shortlist, not ranked 1), R (rank 1)."""
    res, per_query = {}, []
    for run in RUNS:
        meta, cols, groups = load_run(run)
        s1 = cols["global_embedding_first_rank"]
        for variant in ("hybrid_K", "hybrid_hubcorr_K"):
            key = sys_key(cols, variant)
            if key is None or (variant == "hybrid_K" and "hubcorr" in key):
                continue
            h = cols[f"{key}_first_rank"]
            A = s1 > K_LOCKED
            # structural check: outside the shortlist the hybrid ranking IS the Stage-1 ranking
            assert np.array_equal(h[A], s1[A]), f"{run}/{key}: hybrid changed a query without a cover in the shortlist"
            R = ~A & (h == 1)
            B = ~A & (h > 1)
            B_demoted = B & (h > s1)
            B_held = B & (h <= s1)
            res[f"{run}/{key}"] = {
                "A_no_cover_in_shortlist": stats.boot_mean(A, groups),
                "B_cover_in_shortlist_not_top": stats.boot_mean(B, groups),
                "B_demoted_below_stage1": stats.boot_mean(B_demoted, groups),
                "B_not_promoted": stats.boot_mean(B_held, groups),
                "R_cover_at_rank_1": stats.boot_mean(R, groups),
                "reranker_efficiency_R_given_covered": stats.boot_ratio(R, ~A, groups),
                "stage1_already_rank1": stats.boot_mean(s1 == 1, groups),
                "promoted_to_rank1_from_below": stats.boot_mean(R & (s1 > 1), groups),
            }
            if run == "run4":
                for i in range(len(s1)):
                    if variant == "hybrid_K":
                        per_query.append({"query_wid": groups[i], "s1_first": int(s1[i]), "hyb_first": int(h[i]),
                                          "class": "A" if A[i] else ("R" if R[i] else ("B_demoted" if B_demoted[i] else "B_not_promoted"))})
        # hubness: transitions between the uncorrected and corrected hybrid (same shortlist)
        k0, k1 = sys_key(cols, "hybrid_K"), sys_key(cols, "hybrid_hubcorr_K")
        if k0 and k1 and "hubcorr" not in k0:
            h0, h1 = cols[f"{k0}_first_rank"], cols[f"{k1}_first_rank"]
            covered = s1 <= K_LOCKED
            fixed = covered & (h0 > 1) & (h1 == 1)
            broken = covered & (h0 == 1) & (h1 > 1)
            res[f"{run}/hubness_transitions"] = {
                "fixed_B_to_R": stats.boot_mean(fixed, groups), "broken_R_to_B": stats.boot_mean(broken, groups),
                "net_R_gain": stats.boot_delta(h0 == 1, h1 == 1, groups),
                "share_of_B_fixed": stats.boot_ratio(fixed, covered & (h0 > 1), groups),
                "delta_AP": stats.boot_delta(cols[f"{k0}_ap"], cols[f"{k1}_ap"], groups),
            }
    save("X2_failure_decomposition_K30", "ARTIFACT-ANALYSIS", {"K": K_LOCKED, "classes": res},
         ["reports/results/benchmark_per_query*.csv"],
         "Every benchmark query at K = 30 falls in exactly one class. A: Stage 1 put no cover in its top 30, so no reranker can help. "
         "B: a cover was in the shortlist but the hybrid did not rank one first (split into demoted below its Stage-1 rank, or not promoted). "
         "R: a cover at rank 1. Hubness transitions compare the uncorrected and corrected hybrid on identical shortlists. "
         "The hub-domination class (C) of the registry needs the identity of each query's top false positive, which the committed files do not contain (experiment A1 records it).",
         per_query)


# ---------------------------------------------------------------------------- X3
def x3_compute_frontier() -> None:
    """Measured (DTW pairs per query, wall-clock, quality) points plus the coverage ceiling."""
    pts = []
    for run in RUNS:
        meta, cols, _ = load_run(run)
        rt = meta["runtime"]
        n_q, n_c = meta["protocol"]["queries"], meta["protocol"]["candidates"]
        per_pair_rerank = rt["rerank_ms_per_query"] / K_LOCKED
        for m in meta["metrics"]:
            s = m["system"]
            if s == "global_embedding":
                pairs, ms = 0, 1e3 * rt["global_search_s"] / n_q
            elif s.startswith("classical"):
                pairs, ms = n_c - 1, rt.get("alignment_only_ms_per_pair", float("nan")) * (n_c - 1)
            else:
                pairs, ms = K_LOCKED, rt["rerank_ms_per_query"]
            pts.append({"run": run, "system": s, "dtw_pairs_per_query": pairs, "ms_per_query": ms,
                        "frames": meta["locked_from_calibration"].get("n_frames", 96),
                        **{k: m[k] for k in ("MAP", "MRR", "Hit@1", "Hit@10", "median_first_rank")},
                        "ms_per_pair_rerank": per_pair_rerank})
    save("X3_compute_frontier_measured", "ARTIFACT-ANALYSIS",
         {"points": pts, "notes": ["Classical all-pairs rows in run 2 reuse run 1's cached 96-frame alignment matrix and its measured time.",
                                   "Hub-reference cost (200 x 15,000 pairs, one-off per catalogue) is excluded from per-query cost.",
                                   "Per-pair cost differs between batched exhaustive alignment (0.0485 ms at 96 frames) and per-query reranking (0.177 ms at 96, 1.27 ms at 384)."]},
         ["reports/results/benchmark*.json"],
         "Accuracy of every evaluated system against the DTW work it spends per query and its measured wall-clock time. "
         "Only the K = 30 hybrid, Stage 1 and exhaustive alignment were measured; other K values need experiment A1.")


# ---------------------------------------------------------------------------- X4
def x4_oracle_allocation() -> None:
    """Upper bound on adaptive allocation: an oracle that knows each query's first-cover rank."""
    res = {}
    for run in ("run1", "run2", "run4"):
        _, cols, _ = load_run(run)
        kstar = np.sort(cols["global_embedding_first_rank"])
        n = kstar.size
        fixed = [{"K": k, "mean_pairs": float(k), "coverage": float(np.mean(kstar <= k))} for k in KS if k <= 5000]
        # oracle: spend exactly K* on the cheapest queries first, nothing on the rest
        cum = np.cumsum(kstar) / n
        oracle = [{"coverage": float((i + 1) / n), "mean_pairs": float(cum[i])} for i in np.unique(np.linspace(0, n - 1, 400).astype(int))]
        cov30 = float(np.mean(kstar <= K_LOCKED))
        idx = int((kstar <= K_LOCKED).sum()) - 1  # count directly; ceil(cov * n) mis-rounds
        budget_idx = int(np.searchsorted(cum, K_LOCKED, side="right")) - 1
        res[run] = {"fixed_K": fixed, "oracle": oracle,
                    "fixed_K30": {"coverage": cov30, "mean_pairs": 30.0},
                    "oracle_pairs_for_fixed_K30_coverage": float(cum[idx]),
                    "oracle_coverage_at_30_pairs": float((budget_idx + 1) / n),
                    "share_needing_K_over_100": float(np.mean(kstar > 100)), "share_needing_K_over_500": float(np.mean(kstar > 500))}
    save("X4_oracle_allocation_bound", "ARTIFACT-ANALYSIS", {"runs": res},
         ["reports/results/benchmark_per_query*.csv"],
         "Upper bound only. An oracle that knew each query's Stage-1 first-cover rank K* would align exactly K* candidates for the queries it can cover "
         "and none for the rest. The gap to fixed K is the most any adaptive policy could gain in coverage per unit of DTW work; "
         "a real policy must predict K* from Stage-1 signals (experiments D1/E1).")


# ---------------------------------------------------------------------------- X5
def x5_paired_ablations() -> None:
    comps = {}

    def paired(name, run_a, sys_a, run_b, sys_b, what):
        _, ca, ga = load_run(run_a)
        _, cb, gb = load_run(run_b)
        ka, kb = sys_key(ca, sys_a), sys_key(cb, sys_b)
        assert ga == gb
        comps[name] = {"what": what, "a": f"{run_a}/{ka}", "b": f"{run_b}/{kb}",
                       "delta_AP": stats.boot_delta(ca[f"{ka}_ap"], cb[f"{kb}_ap"], ga),
                       "delta_Hit@1": stats.boot_delta(ca[f"{ka}_first_rank"] == 1, cb[f"{kb}_first_rank"] == 1, ga),
                       "delta_Hit@10": stats.boot_delta(ca[f"{ka}_first_rank"] <= 10, cb[f"{kb}_first_rank"] <= 10, ga)}

    paired("resolution_96_to_384", "run2", "hybrid_K", "run3", "hybrid_K", "same encoder (4,780 works, 60 ep), same alpha 0.15, same shortlist; 96 vs 384 frames, no hub correction")
    paired("resolution_96_to_384_hub", "run2", "hybrid_hubcorr", "run3", "hybrid_hubcorr", "as above, both hub-corrected (lambda 0.5 at 96, 0.6 at 384, each from calibration)")
    for run in ("run2", "run3", "run4"):
        paired(f"hub_correction_{run}", run, "hybrid_K", run, "hybrid_hubcorr", "same shortlist; alignment score minus lambda x probe reference")
    paired("hub_correction_classical", "run2", "classical_alignment", "run2", "classical_alignment_hubcorr", "exhaustive alignment, 96 frames")
    for run in RUNS:
        paired(f"rerank_vs_stage1_{run}", run, "global_embedding", run, "hybrid_K", "hybrid K = 30 against its own Stage 1")
    paired("encoder_data_1500_to_4780", "run1", "global_embedding", "run2", "global_embedding", "Stage 1 only: 1,500 vs 4,780 training works, both 60 epochs")
    paired("encoder_epochs_60_to_150", "run2", "global_embedding", "run4", "global_embedding", "Stage 1 only: 60 vs 150 epochs, 4,780 works")
    paired("hybrid_vs_best_classical", "run4", "hybrid_hubcorr", "run2", "classical_alignment_hubcorr", "best hybrid (run 4) vs corrected exhaustive alignment (run 2): different runs, same queries")
    save("X5_paired_ablations_benchmark", "ARTIFACT-ANALYSIS", {"comparisons": comps}, ["reports/results/benchmark_per_query*.csv"],
         "Paired, work-level bootstrap (1,000 cliques, 10,000 resamples) of per-query differences between systems that share the same 13,000 queries. "
         "Comparisons across runs are paired by query but differ in more than one setting where stated.")


# ---------------------------------------------------------------------------- X6
def x6_dev_transfer() -> None:
    pairs = [("base", "", "run1"), ("full96", "_full96", "run2"), ("full384", "_full384", "run3"), ("long384", "_long384", "run4")]
    rows = []
    for name, suf, run in pairs:
        dev = json.loads((RES / f"hybrid_dev{suf}.json").read_text())
        dm = {m["system"]: m for m in dev["metrics"]}
        meta, cols, groups = load_run(run)
        bm = {m["system"]: m for m in meta["metrics"]}
        hk = next(k for k in dm if k.startswith("hybrid"))
        bk = next(k for k in bm if k.startswith("hybrid") and "hubcorr" not in k)
        dev_ci = dev["bootstrap"].get(f"{hk} - global_embedding", {})
        bench_ci = stats.boot_delta(cols["global_embedding_ap"], cols[f"{bk}_ap"], groups)
        rows.append({"config": name, "benchmark_run": run,
                     "dev_stage1_MAP": dm["global_embedding"]["MAP"], "dev_hybrid_MAP": dm[hk]["MAP"], "dev_classical_MAP": dm["classical_alignment"]["MAP"],
                     "dev_delta_hybrid_minus_stage1": dm[hk]["MAP"] - dm["global_embedding"]["MAP"],
                     "dev_delta_ci": [dev_ci.get("ci_low"), dev_ci.get("ci_high")],
                     "dev_shortlist_recall_K30": dev["shortlist_recall"],
                     "bench_stage1_MAP": bm["global_embedding"]["MAP"], "bench_hybrid_MAP": bm[bk]["MAP"],
                     "bench_delta_hybrid_minus_stage1": bench_ci["delta"], "bench_delta_ci": [bench_ci["ci_low"], bench_ci["ci_high"]],
                     "bench_shortlist_recall_K30": meta["shortlist_recall"],
                     "sign_agrees": bool(np.sign(dm[hk]["MAP"] - dm["global_embedding"]["MAP"]) == np.sign(bench_ci["delta"])),
                     "dev_k_sweep": dev["shortlist_ablation"] if "shortlist_ablation" in dev else None})
    save("X6_dev_benchmark_transfer", "ARTIFACT-ANALYSIS", {"rows": rows}, ["reports/results/hybrid_dev*.json", "reports/results/benchmark*.json"],
         "Does the development protocol (20 queries x 120 candidates, one relevant item) predict the benchmark (13,000 x 15,000, twelve)? "
         "Compares the sign and size of the reranking effect, and shortlist recall at the same K, in each configuration.")


# ---------------------------------------------------------------------------- X7
def x7_training_scale() -> None:
    runs = {}
    for name, hist in (("1,500 works, 60 ep", "sweep_base"), ("4,780 works, 60 ep", "encoder_full_train"), ("4,780 works, 150 ep", "encoder_full_long")):
        summary = json.loads((RES / f"training_summary_{hist}.json").read_text())
        with open(RES / f"training_history_{hist}.csv") as fh:
            v = np.array([float(r["val_map"]) for r in csv.DictReader(fh)])
        tail = v[-30:]
        runs[name] = {"best_val_map": summary["best_val_map"], "best_epoch": summary["best_epoch"], "epochs": int(v.size),
                      "train_works": summary.get("train_wids"), "total_seconds": summary.get("total_seconds"),
                      "val_map_slope_last30_per_epoch": float(np.polyfit(np.arange(tail.size), tail, 1)[0]),
                      "val_map_mean_last30": float(tail.mean())}
    bench = {}
    for run, name in (("run1", "1,500 works, 60 ep"), ("run2", "4,780 works, 60 ep"), ("run4", "4,780 works, 150 ep")):
        meta, cols, groups = load_run(run)
        g = next(m for m in meta["metrics"] if m["system"] == "global_embedding")
        bench[name] = {"stage1_MAP": g["MAP"], "stage1_median_first_rank": g["median_first_rank"],
                       "coverage_K30": stats.boot_mean(cols["global_embedding_first_rank"] <= K_LOCKED, groups)}
    save("X7_training_scale", "ARTIFACT-ANALYSIS", {"validation": runs, "benchmark_stage1": bench},
         ["reports/results/training_summary_*.json", "reports/results/training_history_*.csv", "reports/results/benchmark*.json"],
         "Stage-1 quality against training data and duration, from the three committed encoders. "
         "The slope of validation MAP over the last 30 epochs indicates whether more epochs are likely to help.")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for fn in (x0_reproduction, x1_coverage, x2_failure_decomposition, x3_compute_frontier, x4_oracle_allocation,
               x5_paired_ablations, x6_dev_transfer, x7_training_scale):
        fn()
        print(f"done {fn.__name__}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
