"""Paper tables, generated only from result files. Markdown -> research/tables/, LaTeX -> paper/generated/.

    python research/scripts/make_tables.py

Tables whose inputs do not exist yet are skipped and listed in research/tables/MISSING.txt.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rrlib  # noqa: E402

REPO = rrlib.REPO
RES = REPO / "research" / "results"
MD = REPO / "research" / "tables"
TEX = REPO / "paper" / "generated"
MISSING: list[str] = []


def load(exp: str) -> dict | None:
    p = RES / exp / "metrics.json"
    if not p.exists():
        MISSING.append(exp)
        return None
    return json.loads(p.read_text())


def ci(e: dict, d: int = 3, pct: bool = False) -> str:
    f = (lambda v: f"{100 * v:.1f}") if pct else (lambda v: f"{v:.{d}f}")
    return f"{f(e['estimate'])} [{f(e['ci_low'])}, {f(e['ci_high'])}]"


def dci(e: dict, d: int = 4) -> str:
    return f"{e['delta']:+.{d}f} [{e['ci_low']:+.{d}f}, {e['ci_high']:+.{d}f}]"


def write(name: str, caption: str, head: list[str], rows: list[list[str]], source: str) -> None:
    md = [f"**{caption}**", "", "| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    md += ["| " + " | ".join(r) + " |" for r in rows]
    md += ["", f"<sub>Generated by research/scripts/make_tables.py from {source}.</sub>", ""]
    (MD / f"{name}.md").write_text("\n".join(md))

    def esc(s: str) -> str:
        return s.replace("%", r"\%").replace("&", r"\&").replace("_", r"\_").replace("#", r"\#").replace("≥", r"$\geq$").replace("×", r"$\times$").replace("λ", r"$\lambda$").replace("α", r"$\alpha$").replace("→", r"$\rightarrow$").replace("|", r"$|$")

    tex = [f"% generated by research/scripts/make_tables.py from {source}; do not edit",
           r"\begin{table}[t]\centering\small", rf"\caption{{{esc(caption)}}}\label{{tab:{name}}}",
           r"\begin{tabular}{" + "l" * len(head) + "}", r"\toprule", " & ".join(esc(h) for h in head) + r" \\", r"\midrule"]
    tex += [" & ".join(esc(c) for c in r) + r" \\" for r in rows]
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (TEX / f"{name}.tex").write_text("\n".join(tex))
    print(f"wrote {name}")


def t1_protocol() -> None:
    ds = json.loads((REPO / "data/manifests/manifest_info.json").read_text())
    b = json.loads((REPO / "reports/results/benchmark_long384.json").read_text())["protocol"]
    rc = ds["role_counts"]
    rows = [["Cover Analysis · train", f"{rc['train']['wids']:,}", f"{rc['train']['tracks']:,}", "encoder training"],
            ["Cover Analysis · validation", f"{rc['validation']['wids']}", f"{rc['validation']['tracks']}", "checkpoint selection"],
            ["Cover Analysis · calibration", f"{rc['calibration']['wids']}", f"{rc['calibration']['tracks']}", "α, λ, resolution; nothing else"],
            ["Cover Analysis · dev queries + distractors", f"{rc['query']['wids'] + rc['distractor']['wids']}", f"{rc['query']['tracks'] + rc['distractor']['tracks']}", "development protocol (20 × 120)"],
            ["Benchmark", "3,000", f"{b['candidates']:,}", f"test only: {b['queries']:,} queries, {b['noise_tracks']:,} noise tracks, 12 relevant per query"]]
    write("t1_protocol", "Data and evaluation protocol (all splits work-disjoint)", ["split", "works", "recordings", "used for"], rows,
          "data/manifests/manifest_info.json, reports/results/benchmark_long384.json")


def t2_baselines() -> None:
    x3 = load("X3_compute_frontier_measured")
    if not x3:
        return
    rows = []
    for p in x3["points"]:
        if p["system"].startswith("rerank_only"):
            continue
        rows.append([p["run"].replace("run", "Run "), p["system"].replace("_K30", " K=30").replace("_alpha", " α=").replace("_", " "),
                     f"{p['MAP']:.3f}", f"{p['MRR']:.3f}", f"{p['Hit@1']:.3f}", f"{p['Hit@10']:.3f}", f"{p['median_first_rank']:g}",
                     f"{p['dtw_pairs_per_query']:,}", f"{p['ms_per_query']:.2f}" if p["ms_per_query"] == p["ms_per_query"] else "—"])
    write("t2_baselines", "Frozen benchmark systems: four separate evaluations (13,000 queries × 15,000 candidates)",
          ["run", "system", "MAP", "MRR", "Hit@1", "Hit@10", "med. rank", "DTW pairs/query", "ms/query"], rows, "research/results/X3_compute_frontier_measured")


def t3_ablations() -> None:
    x5 = load("X5_paired_ablations_benchmark")
    if not x5:
        return
    rows = [[k.replace("_", " "), v["what"], dci(v["delta_AP"]), dci(v["delta_Hit@1"], 3)] for k, v in x5["comparisons"].items()]
    write("t3_ablations", "Paired ablations on the benchmark (Δ = b − a, work-level 95% CI)", ["comparison", "setting", "Δ AP", "Δ Hit@1"], rows,
          "research/results/X5_paired_ablations_benchmark")


def t5_failures() -> None:
    x2 = load("X2_failure_decomposition_K30")
    if not x2:
        return
    rows = []
    for k, v in x2["classes"].items():
        if "transitions" in k:
            continue
        rows.append([k.split("/")[0].replace("run", "Run "), "hub-corrected" if "hubcorr" in k else "uncorrected",
                     ci(v["A_no_cover_in_shortlist"], pct=True), ci(v["B_demoted_below_stage1"], pct=True), ci(v["B_not_promoted"], pct=True),
                     ci(v["R_cover_at_rank_1"], pct=True), ci(v["reranker_efficiency_R_given_covered"], pct=True)])
    write("t5_failures", "Failure classes at K = 30, % of 13,000 queries (work-level 95% CI)",
          ["run", "reranker", "A: no cover in top 30", "B: demoted", "B: not promoted", "R: rank 1", "R given covered"], rows,
          "research/results/X2_failure_decomposition_K30")


def t6_coverage() -> None:
    x1 = load("X1_stage1_coverage")
    if not x1:
        return
    ks = ["10", "30", "100", "500", "1000"]
    names = {"run1": "Stage 1 · 1,500 works, 60 ep", "run2": "Stage 1 · 4,780 works, 60 ep", "run4": "Stage 1 · 4,780 works, 150 ep",
             "run2/classical_alignment": "exhaustive alignment, 96 fr.", "run2/classical_alignment_hubcorr": "exhaustive alignment + hub corr."}
    rows = [[names[k]] + [ci(v["curve"][kk], pct=True) for kk in ks] for k, v in x1["coverage"].items()]
    write("t6_coverage", "Coverage C(K): % of queries with ≥ 1 cover in the top K (work-level 95% CI)", ["ranking", *[f"K = {k}" for k in ks]], rows,
          "research/results/X1_stage1_coverage")


def t_local() -> None:
    a1 = load("A1_k_sweep_long384")
    if a1:
        rows = [[str(e["K"]), f"{e['coverage']:.3f}", f"{e['shortlist_recall']:.3f}", f"{e['hub']['MAP']:.4f}", f"{e['hub']['Hit@1']:.3f}",
                 f"{e['hub']['Hit@10']:.3f}", f"{e['est_rerank_ms_per_query']:.0f}"] for e in a1["by_k"]]
        write("t4_k_sweep", f"Shortlist size K: coverage, recall and hub-corrected hybrid quality ({a1['evidence']})",
              ["K", "coverage", "shortlist recall", "MAP", "Hit@1", "Hit@10", "rerank ms/query"], rows, "research/results/A1_k_sweep_long384")
    e1 = load("E1_adaptive_k")
    if e1:
        rows = []
        for menu, res in e1["menus"].items():
            for b, r in res.items():
                rows.append([menu, b.replace("budget", ""), f"{r['realised_mean_K']:.1f}", f"{r['policy_MAP']:.4f}", f"{r['fixed_MAP']:.4f}",
                             dci(r["delta_AP_policy_minus_fixed"]), dci(r["delta_Hit1_policy_minus_fixed"], 3)])
        write("t7_adaptive_k", f"Adaptive vs fixed K at equal budget ({e1['evidence']})",
              ["menu", "budget K", "realised mean K", "policy MAP", "fixed MAP", "Δ AP", "Δ Hit@1"], rows, "research/results/E1_adaptive_k")


def numbers() -> None:
    """LaTeX macros for every number the paper's prose quotes, computed from result files."""
    import math

    x1, x2, x4, x6 = load("X1_stage1_coverage"), load("X2_failure_decomposition_K30"), load("X4_oracle_allocation_bound"), load("X6_dev_benchmark_transfer")
    if not (x1 and x2 and x4 and x6):
        return
    c = x2["classes"]
    r1, r4h, r4 = c["run1/hybrid_K30_alpha0.05"], c["run4/hybrid_hubcorr_K30_alpha0.10"], c["run4/hybrid_K30_alpha0.10"]
    tr4 = c["run4/hubness_transitions"]
    pct = lambda v: f"{100 * v:.1f}"  # noqa: E731
    cov1, cov4 = 1 - r1["A_no_cover_in_shortlist"]["estimate"], 1 - r4h["A_no_cover_in_shortlist"]["estimate"]
    e1, e4 = r1["reranker_efficiency_R_given_covered"]["estimate"], r4h["reranker_efficiency_R_given_covered"]["estimate"]
    h1, h4 = r1["R_cover_at_rank_1"]["estimate"], r4h["R_cover_at_rank_1"]["estimate"]
    share_cov = math.log(cov4 / cov1) / math.log(h4 / h1)
    cross = x1["paired_embedding_minus_corrected_alignment"]
    dev = x6["rows"]
    m = {
        "MissThirty": pct(r4h["A_no_cover_in_shortlist"]["estimate"]), "MissThirtyLo": pct(r4h["A_no_cover_in_shortlist"]["ci_low"]),
        "MissThirtyHi": pct(r4h["A_no_cover_in_shortlist"]["ci_high"]), "MissThirtyRunOne": pct(r1["A_no_cover_in_shortlist"]["estimate"]),
        "CovRunOne": f"{cov1:.3f}", "CovRunFour": f"{cov4:.3f}", "EffRunOne": f"{e1:.3f}", "EffRunFour": f"{e4:.3f}",
        "EffRunFourPct": pct(e4), "EffRunFourLo": pct(r4h["reranker_efficiency_R_given_covered"]["ci_low"]), "EffRunFourHi": pct(r4h["reranker_efficiency_R_given_covered"]["ci_high"]),
        "EffRunFourUncorrPct": pct(r4["reranker_efficiency_R_given_covered"]["estimate"]),
        "HitOneRunOne": f"{h1:.3f}", "HitOneRunFour": f"{h4:.3f}", "HitOneGain": f"{h4 / h1:.1f}", "CoverageShareOfGain": f"{100 * share_cov:.0f}",
        "HubFixedShare": pct(tr4["share_of_B_fixed"]["estimate"]), "HubFixedLo": pct(tr4["share_of_B_fixed"]["ci_low"]), "HubFixedHi": pct(tr4["share_of_B_fixed"]["ci_high"]),
        "HubBroken": pct(tr4["broken_R_to_B"]["estimate"]),
        "CrossTen": f"{100 * cross['10']['delta']:+.1f}", "CrossThirty": f"{100 * cross['30']['delta']:+.1f}",
        "CrossFifty": f"{100 * cross['50']['delta']:+.1f}", "CrossFiftyLo": f"{100 * cross['50']['ci_low']:+.1f}", "CrossFiftyHi": f"{100 * cross['50']['ci_high']:+.1f}",
        "CrossHundred": f"{100 * cross['100']['delta']:+.1f}", "CrossFiveHundred": f"{100 * cross['500']['delta']:+.1f}",
        "OraclePairs": f"{x4['runs']['run4']['oracle_pairs_for_fixed_K30_coverage']:.1f}", "OracleCovAtThirty": pct(x4["runs"]["run4"]["oracle_coverage_at_30_pairs"]),
        "NeedOverHundred": pct(x4["runs"]["run4"]["share_needing_K_over_100"]), "NeedOverFiveHundred": pct(x4["runs"]["run4"]["share_needing_K_over_500"]),
        "DevRecallMin": f"{min(r['dev_shortlist_recall_K30'] for r in dev):.2f}", "DevRecallMax": f"{max(r['dev_shortlist_recall_K30'] for r in dev):.2f}",
        "BenchRecallMin": f"{min(r['bench_shortlist_recall_K30'] for r in dev):.3f}", "BenchRecallMax": f"{max(r['bench_shortlist_recall_K30'] for r in dev):.3f}",
        "DevSignFlips": str(sum(not r["sign_agrees"] for r in dev)), "DevConfigs": str(len(dev)),
    }
    lines = ["% generated by research/scripts/make_tables.py from research/results/X*; do not edit"]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in m.items()]
    (TEX / "numbers.tex").write_text("\n".join(lines) + "\n")
    print("wrote numbers.tex")


def main() -> int:
    MD.mkdir(parents=True, exist_ok=True)
    TEX.mkdir(parents=True, exist_ok=True)
    for fn in (t1_protocol, t2_baselines, t3_ablations, t5_failures, t6_coverage, t_local, numbers):
        fn()
    (MD / "MISSING.txt").write_text("\n".join(sorted(set(MISSING))) + ("\n" if MISSING else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
