"""Paper figures (paper/figures/) and the two small analyses they need, generated only from result files.

    python research/scripts/make_paper_assets.py

Analyses written first, as ordinary result directories (never edited by hand):
  P1_rank1_hub_concentration  where rank-1 false positives come from, by candidate hub reference (A1 files)
  P2_dev_vs_benchmark         the same comparison on the development protocol and on the benchmark, paired

Figures are then drawn from research/results/ and reports/results/ only. Figures made by
make_figures.py and the two error-case figures from reports/figures/ are copied next to them so
paper/figures/ is self-contained.
"""

from __future__ import annotations

import csv
import json
import shutil
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import make_figures as mf  # noqa: E402  (shared palette and matplotlib style)
import rrlib  # noqa: E402
import stats  # noqa: E402

plt = mf.plt
REPO = rrlib.REPO
RES = REPO / "research" / "results"
REP = REPO / "reports" / "results"
OUT = REPO / "paper" / "figures"
SLOT, INK, MUTED = mf.SLOT, mf.INK, mf.MUTED
plt.rcParams.update({"figure.facecolor": "white", "axes.facecolor": "white", "savefig.facecolor": "white"})

COPIED = {  # paper name <- source
    "coverage_by_encoder": REPO / "research/figures/fig2_stage1_coverage.pdf",
    "failure_decomposition_K30": REPO / "research/figures/fig4_failure_decomposition.pdf",
    "hit1_factorisation": REPO / "research/figures/fig7_hit1_factorisation.pdf",
    "k_sweep": REPO / "research/figures/fig8_k_sweep.pdf",
    "failure_by_K": REPO / "research/figures/fig9_failure_by_K.pdf",
    "adaptive_vs_fixed": REPO / "research/figures/fig10_adaptive_vs_fixed.pdf",
    "stage1_variants": REPO / "research/figures/fig11_stage1_variants.pdf",
    "fused_stage1_end_to_end": REPO / "research/figures/fig12_a2_end_to_end.pdf",
    "case_dtw_success_P_797406": REPO / "reports/figures/error_success_P_797406.png",
    "case_shortlist_miss_P_310762": REPO / "reports/figures/error_false_positive_P_310762.png",
}


def rows(path: Path) -> list[dict]:
    with open(path) as fh:
        return list(csv.DictReader(fh))


def jload(path: Path) -> dict:
    return json.loads(path.read_text())


def write_result(name: str, label: str, metrics: dict, sources: list[str], readme: str) -> dict:
    d = RES / name
    d.mkdir(parents=True, exist_ok=True)
    rrlib.write_json(d / "metrics.json", {"experiment_id": name.split("_")[0], "evidence": label, "sources": sources, **metrics})
    (d / "README.md").write_text(f"# {name} ({label})\n\n{readme}\n\nGenerated by `research/scripts/make_paper_assets.py`; do not edit.\n")
    return jload(d / "metrics.json")


def save(fig, name: str, evidence: str) -> None:
    fig.text(0.995, -0.06, evidence, ha="right", va="top", fontsize=6.5, color=MUTED)
    fig.savefig(OUT / f"{name}.pdf", bbox_inches="tight")
    fig.savefig(OUT / f"{name}.png", bbox_inches="tight", dpi=170)
    plt.close(fig)
    print(f"wrote paper/figures/{name}")


# ------------------------------------------------------------------ analyses
def p1_hub_concentration() -> dict:
    a1 = RES / "A1_k_sweep_long384"
    cand = rows(a1 / "candidates.csv")
    ref = np.array([float(c["hub_reference"]) for c in cand])
    kocc = np.array([float(c["kocc10"]) for c in cand])
    pct = {c["candidate_pid"]: float(p) for c, p in zip(cand, (np.argsort(np.argsort(ref)) + 0.5) / len(ref))}
    pq = rows(a1 / "per_query.csv")
    out: dict = {"n_candidates": len(cand), "bins": [f"{10 * i}-{10 * (i + 1)}%" for i in range(10)], "systems": {}}
    for k in (30, 500):
        for s in ("hyb", "hub"):
            fp = [pct[r[f"{s}_top1_K{k}"]] for r in pq if int(r[f"{s}_first_K{k}"]) != 1 and int(r[f"cov_K{k}"]) > 0]
            fp = np.array(fp)
            hist = np.histogram(fp, bins=np.linspace(0, 1, 11))[0]
            out["systems"][f"K{k}/{s}"] = {
                "n_rank1_false_positives_in_covered_queries": int(fp.size),
                "share_by_reference_decile": (hist / max(fp.size, 1)).tolist(),
                "share_top_5pct": float(np.mean(fp >= 0.95)) if fp.size else 0.0,
                "share_top_10pct": float(np.mean(fp >= 0.90)) if fp.size else 0.0,
            }
    rk = np.argsort(np.argsort(ref)), np.argsort(np.argsort(kocc))
    out["spearman_reference_vs_stage1_kocc10"] = float(np.corrcoef(rk[0], rk[1])[0, 1])
    return write_result(
        "P1_rank1_hub_concentration", "ANALYSIS of LOCAL-FULL", out,
        ["research/results/A1_k_sweep_long384/candidates.csv", "research/results/A1_k_sweep_long384/per_query.csv"],
        "For queries whose shortlist contains a cover but whose rank-1 item is not one, where does that rank-1 item sit "
        "in the catalogue-wide distribution of the probe hub reference? Uniform would put 10% in each decile.")


def p2_dev_vs_benchmark() -> dict:
    def bench(csv_path: Path, a: str, b: str) -> dict:
        r = rows(csv_path)
        return stats.boot_delta([float(x[a]) for x in r], [float(x[b]) for x in r], [x["query_wid"] for x in r])

    def dev(file: str, key_block: str, key: str) -> dict:
        d = jload(REP / file)[key_block][key]
        return {"delta": d["delta"], "ci_low": d["ci_low"], "ci_high": d["ci_high"], "n_groups": d["n_groups"]}

    h1 = RES / "H1_alignment_ablation" / "per_query.csv"
    comps = [
        {"question": "hybrid (1,500-work encoder) minus exhaustive classical alignment, 96 frames",
         "dev": dev("hybrid_dev.json", "bootstrap", "hybrid_K30_alpha0.05 - classical_alignment"),
         "benchmark": bench(REP / "benchmark_per_query.csv", "classical_alignment_ap", "hybrid_K30_alpha0.05_ap"),
         "benchmark_source": "run 1"},
        {"question": "reranking minus Stage 1 (150-epoch encoder, 384 frames)",
         "dev": dev("hybrid_dev_long384.json", "bootstrap", "hybrid_K30_alpha0.10 - global_embedding"),
         "benchmark": bench(REP / "benchmark_per_query_long384.csv", "global_embedding_ap", "hybrid_K30_alpha0.10_ap"),
         "benchmark_source": "run 4"},
        {"question": "hub correction of exhaustive classical alignment, 96 frames",
         "dev": {k: jload(REP / "hubness_correction.json")["dev_bootstrap_corrected_minus_uncorrected"][k] for k in ("delta", "ci_low", "ci_high", "n_groups")},
         "benchmark": bench(REP / "benchmark_per_query_full96.csv", "classical_alignment_ap", "classical_alignment_hubcorr_ap"),
         "benchmark_source": "run 2"},
        {"question": "profile-cosine key rotation minus no key handling, 96 frames",
         "dev": {k: -v if k == "delta" else v for k, v in dev("classical_dev.json", "bootstrap_vs_baseline", "classical_none - classical_profile_cosine").items()},
         "benchmark": bench(h1, "none_n96_ap", "profile_cosine_n96_ap"),
         "benchmark_source": "H1 (LOCAL-FULL, K = 30 rerank only)"},
    ]
    # the dev key-rotation interval must be negated too (it was stored as none - rotation)
    d4 = jload(REP / "classical_dev.json")["bootstrap_vs_baseline"]["classical_none - classical_profile_cosine"]
    comps[3]["dev"].update({"ci_low": -d4["ci_high"], "ci_high": -d4["ci_low"]})
    for c in comps:
        c["dev_interval_includes_zero"] = bool(c["dev"]["ci_low"] <= 0 <= c["dev"]["ci_high"])
        c["benchmark_interval_excludes_zero"] = bool(c["benchmark"]["ci_low"] > 0 or c["benchmark"]["ci_high"] < 0)
        c["point_estimates_disagree_in_sign"] = bool(np.sign(c["dev"]["delta"]) != np.sign(c["benchmark"]["delta"]))
    return write_result(
        "P2_dev_vs_benchmark", "ANALYSIS of FROZEN-RUN + DEV (+ LOCAL-FULL for key rotation)", {"comparisons": comps},
        ["reports/results/hybrid_dev*.json", "reports/results/classical_dev.json", "reports/results/hubness_correction.json",
         "reports/results/benchmark_per_query*.csv", "research/results/H1_alignment_ablation/per_query.csv"],
        "Each row: the same paired comparison on the 20-query development protocol (1 relevant item, 119 candidates) and on the "
        "13,000-query benchmark (12 relevant, 14,999 candidates). Deltas are AP, work-level paired bootstrap.")


# ------------------------------------------------------------------ figures
def fig_architecture() -> None:
    r4 = jload(REP / "benchmark_long384.json")
    rt, locked = r4["runtime"], r4["locked_from_calibration"]
    n_c, n_q = r4["protocol"]["candidates"], r4["protocol"]["queries"]
    k = locked["shortlist_k"]
    frac = 100 * k / (n_c - 1)
    boxes = [
        ("HPCP\n12 × T", "Da-TACOS features\n(no audio)"),
        ("TCN encoder\n645,504\nparameters", f"128-d unit vector\n{rt['embedding_s']:.0f} s for {n_c:,} tracks"),
        ("exact cosine\nsearch", f"{rt['global_search_s']:.2f} s for\n{n_q:,} queries"),
        (f"top-K\nshortlist\nK = {k}", f"{frac:.1f}% of candidates\naligned per query"),
        ("key rotation\n(profile\ncosine)", "1 of 12 shifts\nper pair"),
        (f"subsequence\nDTW, {locked['n_frames']}\nframes", f"{rt['rerank_ms_per_query']:.0f} ms per query\nfor K = {k}"),
        ("z-score\nfusion + hub\ncorrection", f"α = {locked['alpha']:.2f}, λ = {locked['hub_correction']['lambda']}\n(calibration works)"),
    ]
    fig, ax = plt.subplots(figsize=(10.5, 2.1))
    ax.set_xlim(0, len(boxes)), ax.set_ylim(0, 1), ax.axis("off")
    for i, (title, note) in enumerate(boxes):
        stage2 = i >= 3
        ax.add_patch(plt.Rectangle((i + 0.06, 0.45), 0.88, 0.45, fc="white", ec=SLOT[1] if stage2 else SLOT[0], lw=1.6))
        ax.text(i + 0.5, 0.675, title, ha="center", va="center", fontsize=7.2, weight="bold", color=INK, linespacing=1.1)
        ax.text(i + 0.5, 0.25, note, ha="center", va="center", fontsize=6.4, color=MUTED)
        if i < len(boxes) - 1:
            ax.annotate("", xy=(i + 1.06, 0.675), xytext=(i + 0.94, 0.675), arrowprops=dict(arrowstyle="->", color=INK, lw=1))
    ax.text(0.06, 0.98, "Stage 1: every candidate", color=SLOT[0], fontsize=7.5, weight="bold", va="bottom")
    ax.text(3.06, 0.98, "Stage 2: only the shortlist", color=SLOT[1], fontsize=7.5, weight="bold", va="bottom")
    save(fig, "architecture", "values: reports/results/benchmark_long384.json (run 4)")


def fig_runs() -> None:
    files = [("Run 1", "benchmark.json"), ("Run 2", "benchmark_full96.json"), ("Run 3", "benchmark_full384.json"), ("Run 4", "benchmark_long384.json")]
    runs = [(lab, {m["system"].split("_K30")[0]: m["MAP"] for m in jload(REP / f)["metrics"]}) for lab, f in files]
    fig, ax = plt.subplots(figsize=(6.6, 3.0))
    series = [("global_embedding", "Stage 1 (embedding)", SLOT[0]), ("hybrid", "hybrid, K = 30", SLOT[3]), ("hybrid_hubcorr", "hybrid + hub corr., K = 30", SLOT[1])]
    for key, lab, c in series:
        xs = [i for i, (_, m) in enumerate(runs) if key in m]
        ys = [runs[i][1][key] for i in xs]
        ax.plot(xs, ys, "-o", color=c, ms=5)
        ax.text(xs[-1] + 0.08, ys[-1], lab, color=c, fontsize=7.5, va="center")
    cl, clh = runs[0][1]["classical_alignment"], runs[1][1]["classical_alignment_hubcorr"]
    ax.axhline(cl, color=MUTED, lw=1, ls=":")
    ax.text(-0.1, cl + 0.003, f"exhaustive alignment, 96 frames ({cl:.3f})", color=MUTED, fontsize=7)
    ax.axhline(clh, color=MUTED, lw=1, ls="--")
    ax.text(-0.1, clh + 0.003, f"exhaustive alignment + hub corr., 96 frames ({clh:.3f})", color=MUTED, fontsize=7)
    ax.set_xticks(range(4), ["Run 1\n1,500 works · 60 ep\n96 fr.", "Run 2\n4,780 works · 60 ep\n96 fr.", "Run 3\n4,780 · 60 ep\n384 fr.", "Run 4\n4,780 · 150 ep\n384 fr."], fontsize=7)
    ax.set_xlim(-0.2, 4.4)
    ax.set_ylabel("MAP (benchmark)")
    ax.set_title("Four locked benchmark evaluations")
    ax.grid(axis="x", visible=False)
    save(fig, "map_by_run", "FROZEN-RUN · reports/results/benchmark*.json · 13,000 queries · exhaustive 384-frame alignment not run")


def fig_frontier() -> None:
    a1, a2 = jload(RES / "A1_k_sweep_long384/metrics.json"), jload(RES / "A2_k_sweep_win_fuse/metrics.json")
    r1, r2 = jload(REP / "benchmark.json"), jload(REP / "benchmark_full96.json")
    n = r1["protocol"]["candidates"] - 1
    mp = lambda r, s: next(m["MAP"] for m in r["metrics"] if m["system"] == s)  # noqa: E731
    fig, ax = plt.subplots(figsize=(6.4, 3.2))
    for run, c, lab in ((a1, SLOT[1], "hybrid + hub corr., global Stage 1 (A1)"), (a2, SLOT[2], "hybrid + hub corr., fused Stage 1 (A2)")):
        ks = [e["K"] for e in run["by_k"]]
        ax.plot(ks, [e["hub"]["MAP"] for e in run["by_k"]], "-o", color=c, ms=3.5, label=lab)
    ax.plot([n], [mp(r1, "classical_alignment")], "s", color=MUTED, ms=6)
    ax.text(n / 1.25, mp(r1, "classical_alignment"), "exhaustive, 96 fr.", ha="right", va="center", fontsize=7, color=MUTED)
    ax.plot([n], [mp(r2, "classical_alignment_hubcorr")], "s", color=INK, ms=6)
    ax.text(n / 1.25, mp(r2, "classical_alignment_hubcorr"), "exhaustive + hub corr., 96 fr.", ha="right", va="center", fontsize=7, color=INK)
    ax.axvline(n, color=MUTED, lw=0.8, ls=":")
    ax.text(n * 1.05, 0.2, "exhaustive\n384 fr.:\nnot run\n(≈ 42 h est.)", fontsize=6.8, color=MUTED, va="top")
    ax.set_xscale("log")
    ax.set_xlim(3.5, n * 4)
    ax.set_xlabel("alignments per query (log)")
    ax.set_ylabel("MAP (benchmark)")
    ax.set_title("Accuracy against alignment work")
    ax.legend(loc="upper left", fontsize=7)
    save(fig, "frontier", "curves: LOCAL-FULL A1/A2 (384 fr., laptop) · squares: FROZEN-RUN runs 1–2 (96 fr.) · different resolutions and machines")


def fig_hub(p1: dict) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 2.8), sharey=True)
    x = np.arange(10)
    for ax, k in zip(axes, (30, 500)):
        for off, s, c, lab in ((-0.2, "hyb", SLOT[3], "uncorrected"), (0.2, "hub", SLOT[1], "hub-corrected")):
            e = p1["systems"][f"K{k}/{s}"]
            ax.bar(x + off, 100 * np.array(e["share_by_reference_decile"]), width=0.38, color=c,
                   label=f"{lab} (n = {e['n_rank1_false_positives_in_covered_queries']:,})")
        ax.axhline(10, color=MUTED, lw=1, ls=":")
        ax.set_xticks(x, [f"{10 * i + 10}" for i in x], fontsize=7)
        ax.set_title(f"K = {k}")
        ax.legend(fontsize=6.8, loc="upper left")
        ax.grid(axis="x", visible=False)
    axes[0].set_ylabel("% of rank-1 false positives")
    fig.supxlabel("candidate's hub-reference percentile (decile upper bound)", fontsize=8.5, y=-0.04)
    save(fig, "hub_concentration", "ANALYSIS of LOCAL-FULL · P1 · queries whose shortlist holds a cover but whose rank-1 item is not one · dotted: uniform")


def fig_resolution() -> None:
    dev96, dev384 = jload(REP / "hybrid_dev.json"), jload(REP / "hybrid_dev_n384.json")
    mp = lambda d, s: next(m["MAP"] for m in d["metrics"] if m["system"] == s)  # noqa: E731
    x5 = jload(RES / "X5_paired_ablations_benchmark/metrics.json")
    h1 = jload(RES / "H1_alignment_ablation/metrics.json")["variants"]
    fig, axes = plt.subplots(1, 3, figsize=(8.6, 2.7), gridspec_kw={"width_ratios": [1, 1, 1.2]})
    ax = axes[0]
    for i, (s96, s384, lab, c) in enumerate((("classical_alignment", "classical_alignment", "classical", MUTED),
                                               ("hybrid_K30_alpha0.05", "hybrid_K30_alpha0.00", "hybrid", SLOT[1]))):
        a, b = mp(dev96, s96), mp(dev384, s384)
        ax.plot([0, 1], [a, b], "-o", color=c)
        ax.text(1.06, b, f"{lab} {a:.3f}→{b:.3f}", fontsize=7, va="center", color=c)
    ax.set_xticks([0, 1], ["96", "384"]), ax.set_xlim(-0.2, 2.8), ax.set_title("Development")
    ax.set_ylabel("MAP"), ax.set_xlabel("frames")
    ax = axes[1]
    comps = x5["comparisons"]
    keys = [k for k in comps if k.startswith("resolution")]
    for i, key in enumerate(keys):
        d = comps[key]["delta_AP"] if "delta_AP" in comps[key] else comps[key]
        ax.plot([i, i], [d["ci_low"], d["ci_high"]], color=SLOT[1], lw=2)
        ax.plot([i], [d["delta"]], "o", color=SLOT[1])
    ax.axhline(0, color=MUTED, lw=1)
    ax.set_xticks(range(len(keys)), ["no hub corr.", "hub-corrected"], fontsize=7), ax.set_xlim(-0.6, len(keys) - 0.4)
    ax.set_title("Benchmark: run 3 − run 2"), ax.set_ylabel("Δ AP, 384 − 96 frames")
    ax = axes[2]
    labs = [("none", "no key"), ("profile_cosine", "profile rot."), ("exhaustive_dtw", "12 rotations")]
    for j, (n, c) in enumerate((("96", SLOT[3]), ("384", SLOT[1]))):
        ax.plot(range(3), [h1[f"{v}_n{n}"]["MAP"] for v, _ in labs], "-o", color=c, label=f"{n} frames")
    ax.set_xticks(range(3), [l for _, l in labs], fontsize=7), ax.set_title("Benchmark: H1, K = 30")
    ax.legend(fontsize=7), ax.set_ylabel("MAP")
    for a in axes:
        a.grid(axis="x", visible=False)
    fig.subplots_adjust(wspace=0.5)
    save(fig, "resolution", "left: DEV · middle: ARTIFACT-ANALYSIS X5 of FROZEN runs 2–3 · right: LOCAL-FULL H1 (run-4 encoder)")


def fig_dev_vs_bench(p2: dict) -> None:
    comps = p2["comparisons"]
    fig, axes = plt.subplots(1, len(comps), figsize=(9.0, 2.7))
    short = ["hybrid − exhaustive\n(run-1 encoder)", "rerank − Stage 1\n(150-ep encoder)", "hub corr. of\nexhaustive, 96 fr.", "key rotation −\nnone, 96 fr."]
    for ax, c, title in zip(axes, comps, short):
        for i, (key, col, lab) in enumerate((("dev", SLOT[3], "dev\n20 q"), ("benchmark", SLOT[0], "bench\n13k q"))):
            d = c[key]
            ax.plot([i, i], [d["ci_low"], d["ci_high"]], color=col, lw=2.2)
            ax.plot([i], [d["delta"]], "o", color=col, ms=5)
        ax.axhline(0, color=MUTED, lw=1)
        ax.set_xticks([0, 1], ["dev\n20 q", "bench\n13k q"], fontsize=7)
        ax.set_xlim(-0.6, 1.6)
        ax.set_title(title, fontsize=8)
        ax.grid(axis="x", visible=False)
    axes[0].set_ylabel("paired Δ AP (95% CI)")
    fig.subplots_adjust(wspace=0.55)
    save(fig, "dev_vs_benchmark", "P2 · DEV vs FROZEN-RUN (key rotation: LOCAL-FULL H1) · work-level paired bootstrap")


def copy_figures() -> None:
    for name, src in COPIED.items():
        if src.exists():
            shutil.copyfile(src, OUT / f"{name}{src.suffix}")
            print(f"copied paper/figures/{name}{src.suffix}")
        else:
            print(f"MISSING {src}")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    p1, p2 = p1_hub_concentration(), p2_dev_vs_benchmark()
    fig_architecture(), fig_runs(), fig_frontier(), fig_hub(p1), fig_resolution(), fig_dev_vs_bench(p2)
    copy_figures()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
