"""Paper tables, generated only from result files. Markdown -> research/tables/, LaTeX -> paper/generated/.

    python research/scripts/make_tables.py

Tables whose inputs do not exist yet are skipped and listed in research/tables/MISSING.txt.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rrlib  # noqa: E402

REPO = rrlib.REPO
RES = REPO / "research" / "results"
MD = REPO / "research" / "tables"
TEX = REPO / "paper" / "tables"
MISSING: list[str] = []


def load(exp: str) -> dict | None:
    p = RES / exp / "metrics.json"
    if not p.exists():
        MISSING.append(exp)
        return None
    return json.loads(p.read_text())


def ci(e: dict, d: int = 3, pct: bool = False) -> str:
    f = (lambda v: f"{100 * v:.1f}") if pct else (lambda v: f"{v:.{d}f}")
    return f"{f(e['estimate'])} [{f(e['ci_low'])}, {f(e['ci_high'])}]"


def dci(e: dict, d: int = 4) -> str:
    return f"{e['delta']:+.{d}f} [{e['ci_low']:+.{d}f}, {e['ci_high']:+.{d}f}]"


def write(name: str, caption: str, head: list[str], rows: list[list[str]], source: str, colspec: str | None = None) -> None:
    md = [f"**{caption}**", "", "| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    md += ["| " + " | ".join(r) + " |" for r in rows]
    md += ["", f"<sub>Generated by research/scripts/make_tables.py from {source}.</sub>", ""]
    (MD / f"{name}.md").write_text("\n".join(md))

    def esc(s: str) -> str:
        return s.replace("%", r"\%").replace("&", r"\&").replace("_", r"\_").replace("#", r"\#").replace("≥", r"$\geq$").replace("×", r"$\times$").replace("λ", r"$\lambda$").replace("α", r"$\alpha$").replace("→", r"$\rightarrow$").replace("|", r"$|$").replace("Δ", r"$\Delta$").replace("·", r"$\cdot$").replace("−", "$-$").replace("≤", r"$\leq$")

    wide = colspec is None and (len(head) >= 5 or any(len(" ".join(r)) > 90 for r in rows))  # scale wide tables to the text width
    tex = [f"% generated by research/scripts/make_tables.py from {source}; do not edit",
           r"\begin{table}[tbp]\centering\small", rf"\caption{{{esc(caption)}}}\label{{tab:{name}}}",
           (r"\resizebox{\linewidth}{!}{" if wide else "") + r"\begin{tabular}{" + (colspec or "l" * len(head)) + "}", r"\toprule", " & ".join(esc(h) for h in head) + r" \\", r"\midrule"]
    tex += [" & ".join(esc(c) for c in r) + r" \\" for r in rows]
    tex += [r"\bottomrule", r"\end{tabular}" + ("}" if wide else ""), r"\end{table}", ""]
    (TEX / f"{name}.tex").write_text("\n".join(tex))
    print(f"wrote {name}")


def t1_protocol() -> None:
    ds = json.loads((REPO / "data/manifests/manifest_info.json").read_text())
    b = json.loads((REPO / "reports/results/benchmark_long384.json").read_text())["protocol"]
    rc = ds["role_counts"]
    rows = [["Cover Analysis · train", f"{rc['train']['wids']:,}", f"{rc['train']['tracks']:,}", "encoder training"],
            ["Cover Analysis · validation", f"{rc['validation']['wids']}", f"{rc['validation']['tracks']}", "checkpoint selection"],
            ["Cover Analysis · calibration", f"{rc['calibration']['wids']}", f"{rc['calibration']['tracks']}", "α, λ, resolution; nothing else"],
            ["Cover Analysis · dev queries + distractors", f"{rc['query']['wids'] + rc['distractor']['wids']}", f"{rc['query']['tracks'] + rc['distractor']['tracks']}", "development protocol (20 × 120)"],
            ["Benchmark", "3,000", f"{b['candidates']:,}", f"test only: {b['queries']:,} queries, {b['noise_tracks']:,} noise tracks, 12 relevant per query"]]
    write("t1_protocol", "Data and evaluation protocol (all splits work-disjoint)", ["split", "works", "recordings", "used for"], rows,
          "data/manifests/manifest_info.json, reports/results/benchmark_long384.json")


def t2_baselines() -> None:
    x3 = load("X3_compute_frontier_measured")
    if not x3:
        return
    rows = []
    for p in x3["points"]:
        if p["system"].startswith("rerank_only"):
            continue
        rows.append([p["run"].replace("run", "Run "), p["system"].replace("_K30", " K=30").replace("_alpha", " α=").replace("_", " "),
                     f"{p['MAP']:.3f}", f"{p['MRR']:.3f}", f"{p['Hit@1']:.3f}", f"{p['Hit@10']:.3f}", f"{p['median_first_rank']:g}",
                     f"{p['dtw_pairs_per_query']:,}", f"{p['ms_per_query']:.2f}" if p["ms_per_query"] == p["ms_per_query"] else "—"])
    write("t2_baselines", "Frozen benchmark systems: four separate evaluations (13,000 queries × 15,000 candidates)",
          ["run", "system", "MAP", "MRR", "Hit@1", "Hit@10", "med. rank", "DTW pairs/query", "ms/query"], rows, "research/results/X3_compute_frontier_measured")


def t3_ablations() -> None:
    x5 = load("X5_paired_ablations_benchmark")
    if not x5:
        return
    rows = [[k.replace("_", " "), v["what"], dci(v["delta_AP"]), dci(v["delta_Hit@1"], 3)] for k, v in x5["comparisons"].items()]
    write("t3_ablations", "Paired ablations on the benchmark (Δ = b − a, work-level 95% CI)", ["comparison", "setting", "Δ AP", "Δ Hit@1"], rows,
          "research/results/X5_paired_ablations_benchmark", colspec=r"p{0.17\linewidth}p{0.31\linewidth}ll")


def t5_failures() -> None:
    x2 = load("X2_failure_decomposition_K30")
    if not x2:
        return
    rows = []
    for k, v in x2["classes"].items():
        if "transitions" in k:
            continue
        rows.append([k.split("/")[0].replace("run", "Run "), "hub-corrected" if "hubcorr" in k else "uncorrected",
                     ci(v["A_no_cover_in_shortlist"], pct=True), ci(v["B_demoted_below_stage1"], pct=True), ci(v["B_not_promoted"], pct=True),
                     ci(v["R_cover_at_rank_1"], pct=True), ci(v["reranker_efficiency_R_given_covered"], pct=True)])
    write("t5_failures", "Failure classes at K = 30, % of 13,000 queries (work-level 95% CI)",
          ["run", "reranker", "A: no cover in top 30", "B: demoted", "B: not promoted", "R: rank 1", "R given covered"], rows,
          "research/results/X2_failure_decomposition_K30")


def t6_coverage() -> None:
    x1 = load("X1_stage1_coverage")
    if not x1:
        return
    ks = ["10", "30", "100", "500", "1000"]
    names = {"run1": "Stage 1 · 1,500 works, 60 ep", "run2": "Stage 1 · 4,780 works, 60 ep", "run4": "Stage 1 · 4,780 works, 150 ep",
             "run2/classical_alignment": "exhaustive alignment, 96 fr.", "run2/classical_alignment_hubcorr": "exhaustive alignment + hub corr."}
    rows = [[names[k]] + [ci(v["curve"][kk], pct=True) for kk in ks] for k, v in x1["coverage"].items()]
    write("t6_coverage", "Coverage C(K): % of queries with ≥ 1 cover in the top K (work-level 95% CI)", ["ranking", *[f"K = {k}" for k in ks]], rows,
          "research/results/X1_stage1_coverage")


def t_local() -> None:
    a1 = load("A1_k_sweep_long384")
    if a1:
        rows = [[str(e["K"]), f"{e['coverage']:.3f}", f"{e['shortlist_recall']:.3f}", f"{e['hub']['MAP']:.4f}", f"{e['hub']['Hit@1']:.3f}",
                 f"{e['hub']['Hit@10']:.3f}", f"{e['est_rerank_ms_per_query']:.0f}"] for e in a1["by_k"]]
        write("t4_k_sweep", f"Shortlist size K: coverage, recall and hub-corrected hybrid quality ({a1['evidence']})",
              ["K", "coverage", "shortlist recall", "MAP", "Hit@1", "Hit@10", "rerank ms/query"], rows, "research/results/A1_k_sweep_long384")
    e1 = load("E1_adaptive_k")
    if e1:
        rows = []
        for menu, res in e1["menus"].items():
            for b, r in res.items():
                rows.append([menu, b.replace("budget", ""), f"{r['realised_mean_K']:.1f}", f"{r['policy_MAP']:.4f}", f"{r['fixed_MAP']:.4f}",
                             dci(r["delta_AP_policy_minus_fixed"]), dci(r["delta_Hit1_policy_minus_fixed"], 3)])
        write("t7_adaptive_k", f"Adaptive vs fixed K at equal budget ({e1['evidence']})",
              ["menu", "budget K", "realised mean K", "policy MAP", "fixed MAP", "Δ AP", "Δ Hit@1"], rows, "research/results/E1_adaptive_k")


F1_NAMES = {"win_fuse": "global + 3 windows, fused", "ttr": "test-time 12 key rotations", "s1_hub": "Stage-1 hub corr. (calibration chose λ = 0: identical to reference)",
            "win_max": "3 windows only (MaxSim)", "global:full_60": "encoder: 60 epochs", "global:base_1500": "encoder: 1,500 training works"}
H1_NAMES = {"none": "no key rotation", "profile_cosine": "profile-cosine rotation (locked)", "exhaustive_dtw": "exhaustive 12-rotation DTW"}


def t_local_more() -> None:
    b1 = load("B1_failure_by_K")
    if b1:
        cls = b1["classes"]
        ks = sorted({int(k.split("/")[0][1:]) for k in cls})
        rows = []
        for k in ks:
            h, u = cls[f"K{k}/hub"], cls[f"K{k}/hyb"]
            rows.append([str(k), ci(h["A_no_cover"], pct=True), ci(h["B_hub_top1"], pct=True), ci(h["B_other"], pct=True), ci(h["R_rank1"], pct=True),
                         ci(h["efficiency_R_given_covered"], pct=True), f"{100 * u['B_hub_top1']['estimate']:.1f}"])
        write("t8_failure_by_K", f"Failure classes by K, hub-corrected hybrid, % of queries ({b1['evidence']})",
              ["K", "A: no cover in top K", "B: hub at rank 1", "B: other", "R: cover at rank 1", "R given covered", "B hub, uncorrected"], rows,
              "research/results/B1_failure_by_K")
    d1 = load("D1_query_uncertainty")
    if d1:
        uni = sorted(d1["univariate_auroc"].items(), key=lambda kv: -abs(kv[1]["auroc_for_no_cover"] - 0.5))
        rows = [["cross-fitted logistic model (all signals)", ci(d1["cross_fitted_auroc"])]]
        rows += [[name.replace("_", " "), f"{v['auroc_for_no_cover']:.3f}"] for name, v in uni]
        write("t9_query_uncertainty", f"Predicting 'no cover in the top 30' from label-free Stage-1 signals: AUROC (base rate {100 * d1['base_rate']:.1f}%; below 0.5 = higher for coverable queries; {d1['evidence']})",
              ["signal", "AUROC"], rows, "research/results/D1_query_uncertainty")
    f1 = load("F1s_stage1_summary")
    if f1:
        pc, cur = f1["paired_coverage"], f1["curves"]
        base = f1["base"]
        rows = [["global, 150 epochs, 4,780 works (reference)", ci(cur[base]["@30"]["coverage"], pct=True), ci(cur[base]["@100"]["coverage"], pct=True), "", ""]]
        order = sorted(F1_NAMES, key=lambda v: -pc[f"{v} - {base} @30"]["delta"])
        for v in order:
            rows.append([F1_NAMES[v], ci(cur[v]["@30"]["coverage"], pct=True), ci(cur[v]["@100"]["coverage"], pct=True),
                         pdci(pc[f"{v} - {base} @30"]), pdci(pc[f"{v} - {base} @100"])])
        write("t10_stage1_variants", f"Stage-1 variants: coverage at K = 30 and 100, paired Δ vs the reference, points ({f1['evidence']})",
              ["Stage 1", "coverage@30 (%)", "coverage@100 (%)", "Δ@30", "Δ@100"], rows, "research/results/F1s_stage1_summary")
    h1, h1s = load("H1_alignment_ablation"), load("H1s_alignment_summary")
    if h1 and h1s:
        ref = h1s["reference"]
        rows = []
        for v, r in h1["variants"].items():
            rot, n = v.rsplit("_n", 1)
            key = f"{v} - {ref}"
            d = h1s["comparisons"].get(key)
            rows.append([H1_NAMES.get(rot, rot), n, f"{r['MAP']:.4f}", f"{r['Hit@1']:.3f}",
                         dci(d["delta_AP"]) if d else "reference", dci(d["delta_Hit1"], 3) if d else ""])
        write("t11_alignment_ablation", f"Alignment ablation at K = {h1['K']}, rerank only ({h1['evidence']}); Δ vs the locked profile-cosine rotation at 384 frames",
              ["key handling", "frames", "MAP", "Hit@1", "Δ AP", "Δ Hit@1"], rows, "research/results/H1_alignment_ablation, H1s_alignment_summary")
    c1 = load("C1_hybrid_vs_exhaustive_posthoc")
    if c1:
        rows = []
        for key, r in c1["comparisons"].items():
            k, sysname = key.split("/")
            if sysname != "hub":
                continue
            rows.append([k[1:], f"{r['alignments_per_query_hybrid']:,} vs {r['alignments_per_query_exhaustive']:,}",
                         dci(r["delta_AP_hybrid_minus_exhaustive"]), dci(r["delta_Hit1_hybrid_minus_exhaustive"], 3)])
        write("t12_hybrid_vs_exhaustive", f"POST-HOC, not registered: hub-corrected hybrid at K vs exhaustive corrected alignment ({c1['reference']}); paired Δ, work-level 95% CI",
              ["K", "alignments per query", "Δ AP", "Δ Hit@1"], rows, "research/results/C1_hybrid_vs_exhaustive_posthoc")


def t_a2() -> None:
    a1, a2, a2s = load("A1_k_sweep_long384"), load("A2_k_sweep_win_fuse"), load("A2s_win_fuse_end_to_end")
    if not (a1 and a2 and a2s):
        return
    b1 = {e["K"]: e for e in a1["by_k"]}
    rows = []
    for e in a2["by_k"]:
        k, c = e["K"], a2s["comparisons"][f"K{e['K']}/hub"]
        rows.append([str(k), f"{b1[k]['coverage']:.3f} → {e['coverage']:.3f}", f"{b1[k]['hub']['MAP']:.4f} → {e['hub']['MAP']:.4f}",
                     dci(c["delta_AP"]), f"{100 * c['delta_Hit1']['delta']:+.1f} [{100 * c['delta_Hit1']['ci_low']:+.1f}, {100 * c['delta_Hit1']['ci_high']:+.1f}]"])
    write("t13_a2_end_to_end", f"Registered A2: fused global + window Stage 1 vs global Stage 1, hub-corrected hybrid, paired ({a2['evidence']}; criterion met: {'yes' if a2s['meets_registered_criterion'] else 'no'})",
          ["K", "coverage A1 → A2", "MAP A1 → A2", "Δ AP", "Δ Hit@1 (points)"], rows, "research/results/A2_k_sweep_win_fuse, A2s_win_fuse_end_to_end")


def pdci(e: dict) -> str:
    return f"{100 * e['delta']:+.1f} [{100 * e['ci_low']:+.1f}, {100 * e['ci_high']:+.1f}]"


def numbers_local() -> None:
    """Macros for the local-run results (A1, B1, D1, E1, F1, H1, C1); written only when every input exists."""
    a1, b1, d1, e1 = load("A1_k_sweep_long384"), load("B1_failure_by_K"), load("D1_query_uncertainty"), load("E1_adaptive_k")
    f1, h1s, c1, h1 = load("F1s_stage1_summary"), load("H1s_alignment_summary"), load("C1_hybrid_vs_exhaustive_posthoc"), load("H1_alignment_ablation")
    if not all((a1, b1, d1, e1, f1, h1s, c1, h1)):
        return
    byk = {e["K"]: e for e in a1["by_k"]}
    cls = b1["classes"]
    pct = lambda v: f"{100 * v:.1f}"  # noqa: E731
    cells = [r for res in e1["menus"].values() for r in res.values()]
    nontrivial = [r for r in cells if r["delta_AP_policy_minus_fixed"]["excludes_zero"] and r["delta_AP_policy_minus_fixed"]["delta"] > 0]
    pc, base = f1["paired_coverage"], f1["base"]
    hc = h1s["comparisons"]
    ref = h1s["reference"]
    m = {
        "ReproPass": "exact" if all(c.get("abs_diff", 0) == 0 for c in a1["reproduction"]["checks"].values()) and a1["reproduction"]["pass"] else "within tolerance",
        "AlignMsPerPair": f"{json.loads((RES / 'A1_k_sweep_long384' / 'runtime.json').read_text())['ms_per_aligned_pair']:.2f}",
    }
    for k, name in ((5, "Five"), (30, "Thirty"), (50, "Fifty"), (100, "Hundred"), (200, "TwoHundred"), (500, "FiveHundred")):
        e = byk[k]
        m[f"SweepMap{name}"] = f"{e['hub']['MAP']:.3f}"
        m[f"SweepHit{name}"] = pct(e["hub"]["Hit@1"])
        m[f"SweepCov{name}"] = pct(e["coverage"])
        m[f"SweepMs{name}"] = f"{e['est_rerank_ms_per_query']:.0f}"
        h = cls[f"K{k}/hub"]
        m[f"ClassA{name}"] = pct(h["A_no_cover"]["estimate"])
        m[f"ClassB{name}"] = pct(h["B_hub_top1"]["estimate"] + h["B_other"]["estimate"])
        m[f"Eff{name}"] = pct(h["efficiency_R_given_covered"]["estimate"])
        m[f"HubGain{name}"] = f"{e['hub']['MAP'] - e['hyb']['MAP']:.3f}"
    m.update({
        "DOneAuroc": f"{d1['cross_fitted_auroc']['estimate']:.2f}", "DOneAurocLo": f"{d1['cross_fitted_auroc']['ci_low']:.2f}",
        "DOneAurocHi": f"{d1['cross_fitted_auroc']['ci_high']:.2f}", "DOneBase": pct(d1["base_rate"]),
        "EOneCells": str(len(cells)), "EOneMeets": str(sum(r["meets_registered_criterion"] for r in cells)),
        "EOneApPositive": str(len(nontrivial)),
        "EOneApMax": f"{max(r['delta_AP_policy_minus_fixed']['delta'] for r in cells):.4f}",
        "EOneHitWorstPts": f"{100 * min(r['delta_Hit1_policy_minus_fixed']['delta'] for r in cells):.1f}",
        "EOneHitBetter": str(sum(r["delta_Hit1_policy_minus_fixed"]["delta"] > 0 and r["delta_Hit1_policy_minus_fixed"]["excludes_zero"] for r in cells)),
    })
    for v, name in (("win_fuse", "Fuse"), ("ttr", "Ttr"), ("win_max", "WinMax"), ("global:full_60", "Sixty"), ("global:base_1500", "Small")):
        for kk in ("30", "100"):
            d = pc[f"{v} - {base} @{kk}"]
            tag = "Thirty" if kk == "30" else "Hundred"
            m[f"FOne{name}{tag}"] = f"{100 * d['delta']:+.1f}"
            m[f"FOne{name}{tag}Lo"] = f"{100 * d['ci_low']:+.1f}"
            m[f"FOne{name}{tag}Hi"] = f"{100 * d['ci_high']:+.1f}"
    lam = json.loads((RES / "F1_stage1_variants" / "metrics.json").read_text())["notes"]["s1_hub"]["locked_lambda"]
    m["FOneHubLambda"] = f"{lam:g}"
    for v, name in (("none_n384", "NoRot"), ("exhaustive_dtw_n384", "Exh"), ("profile_cosine_n96", "Short"), ("exhaustive_dtw_n96", "ExhShort")):
        d = hc[f"{v} - {ref}"]
        m[f"HOne{name}Ap"] = f"{d['delta_AP']['delta']:+.4f}"
        m[f"HOne{name}ApLo"] = f"{d['delta_AP']['ci_low']:+.4f}"
        m[f"HOne{name}ApHi"] = f"{d['delta_AP']['ci_high']:+.4f}"
        m[f"HOne{name}Hit"] = f"{100 * d['delta_Hit1']['delta']:+.1f}"
    m["HOneRefMap"] = f"{h1['variants'][ref]['MAP']:.4f}"
    for k, name in ((30, "Thirty"), (50, "Fifty"), (100, "Hundred")):
        r = c1["comparisons"][f"K{k}/hub"]
        m[f"COne{name}Ap"] = f"{r['delta_AP_hybrid_minus_exhaustive']['delta']:+.4f}"
        m[f"COne{name}ApLo"] = f"{r['delta_AP_hybrid_minus_exhaustive']['ci_low']:+.4f}"
        m[f"COne{name}ApHi"] = f"{r['delta_AP_hybrid_minus_exhaustive']['ci_high']:+.4f}"
        m[f"COne{name}Hit"] = f"{100 * r['delta_Hit1_hybrid_minus_exhaustive']['delta']:+.1f}"
        m[f"COne{name}HitLo"] = f"{100 * r['delta_Hit1_hybrid_minus_exhaustive']['ci_low']:+.1f}"
        m[f"COne{name}HitHi"] = f"{100 * r['delta_Hit1_hybrid_minus_exhaustive']['ci_high']:+.1f}"
    a2, a2s = load("A2_k_sweep_win_fuse"), load("A2s_win_fuse_end_to_end")
    if a2 and a2s:
        by2 = {e["K"]: e for e in a2["by_k"]}
        m["ATwoMeets"] = "met" if a2s["meets_registered_criterion"] else "not met"
        m["ATwoAllKPositive"] = "every" if all(v["delta_AP"]["ci_low"] > 0 for v in a2s["comparisons"].values()) else "not every"
        for k, name in ((5, "Five"), (30, "Thirty"), (100, "Hundred"), (500, "FiveHundred")):
            c = a2s["comparisons"][f"K{k}/hub"]
            m[f"ATwoMap{name}"] = f"{by2[k]['hub']['MAP']:.3f}"
            m[f"ATwoHit{name}"] = pct(by2[k]["hub"]["Hit@1"])
            m[f"ATwoAp{name}"] = f"{c['delta_AP']['delta']:+.3f}"
            m[f"ATwoAp{name}Lo"] = f"{c['delta_AP']['ci_low']:+.3f}"
            m[f"ATwoAp{name}Hi"] = f"{c['delta_AP']['ci_high']:+.3f}"
            m[f"ATwoHitD{name}"] = f"{100 * c['delta_Hit1']['delta']:+.1f}"
            m[f"ATwoHitD{name}Lo"] = f"{100 * c['delta_Hit1']['ci_low']:+.1f}"
            m[f"ATwoHitD{name}Hi"] = f"{100 * c['delta_Hit1']['ci_high']:+.1f}"
        m["ATwoRelThirty"] = f"{100 * (by2[30]['hub']['MAP'] / byk[30]['hub']['MAP'] - 1):.0f}"
        m["ATwoStageOneMap"] = f"{a2['stage1']['MAP']:.3f}"
        # smallest A2 K whose MAP reaches A1's MAP at K = 30 (same quality, fewer alignments)
        m["ATwoMatchK"] = str(min(k for k in by2 if by2[k]["hub"]["MAP"] >= byk[30]["hub"]["MAP"]))
        m["ATwoFuseSeconds"] = f"{json.loads((RES / 'A2_k_sweep_win_fuse' / 'runtime.json').read_text())['win_fuse_s']:.0f}"
        m["ATwoAlignMinutes"] = f"{json.loads((RES / 'A2_k_sweep_win_fuse' / 'runtime.json').read_text())['align_top_kmax_s'] / 60:.0f}"
    lines = ["% generated by research/scripts/make_tables.py from research/results/{A1,A2,B1,C1,D1,E1,F1,H1}*; do not edit"]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in m.items()]
    (TEX / "numbers_local.tex").write_text("\n".join(lines) + "\n")
    print("wrote numbers_local.tex")


def numbers() -> None:
    """LaTeX macros for every number the paper's prose quotes, computed from result files."""
    import math

    x1, x2, x4, x6 = load("X1_stage1_coverage"), load("X2_failure_decomposition_K30"), load("X4_oracle_allocation_bound"), load("X6_dev_benchmark_transfer")
    if not (x1 and x2 and x4 and x6):
        return
    c = x2["classes"]
    r1, r4h, r4 = c["run1/hybrid_K30_alpha0.05"], c["run4/hybrid_hubcorr_K30_alpha0.10"], c["run4/hybrid_K30_alpha0.10"]
    tr4 = c["run4/hubness_transitions"]
    pct = lambda v: f"{100 * v:.1f}"  # noqa: E731
    cov1, cov4 = 1 - r1["A_no_cover_in_shortlist"]["estimate"], 1 - r4h["A_no_cover_in_shortlist"]["estimate"]
    e1, e4 = r1["reranker_efficiency_R_given_covered"]["estimate"], r4h["reranker_efficiency_R_given_covered"]["estimate"]
    h1, h4 = r1["R_cover_at_rank_1"]["estimate"], r4h["R_cover_at_rank_1"]["estimate"]
    share_cov = math.log(cov4 / cov1) / math.log(h4 / h1)
    cross = x1["paired_embedding_minus_corrected_alignment"]
    dev = x6["rows"]
    m = {
        "MissThirty": pct(r4h["A_no_cover_in_shortlist"]["estimate"]), "MissThirtyLo": pct(r4h["A_no_cover_in_shortlist"]["ci_low"]),
        "MissThirtyHi": pct(r4h["A_no_cover_in_shortlist"]["ci_high"]), "MissThirtyRunOne": pct(r1["A_no_cover_in_shortlist"]["estimate"]),
        "CovRunOne": f"{cov1:.3f}", "CovRunFour": f"{cov4:.3f}", "EffRunOne": f"{e1:.3f}", "EffRunFour": f"{e4:.3f}",
        "EffRunFourPct": pct(e4), "EffRunFourLo": pct(r4h["reranker_efficiency_R_given_covered"]["ci_low"]), "EffRunFourHi": pct(r4h["reranker_efficiency_R_given_covered"]["ci_high"]),
        "EffRunFourUncorrPct": pct(r4["reranker_efficiency_R_given_covered"]["estimate"]),
        "HitOneRunOne": f"{h1:.3f}", "HitOneRunFour": f"{h4:.3f}", "HitOneGain": f"{h4 / h1:.1f}", "CoverageShareOfGain": f"{100 * share_cov:.0f}",
        "HubFixedShare": pct(tr4["share_of_B_fixed"]["estimate"]), "HubFixedLo": pct(tr4["share_of_B_fixed"]["ci_low"]), "HubFixedHi": pct(tr4["share_of_B_fixed"]["ci_high"]),
        "HubBroken": pct(tr4["broken_R_to_B"]["estimate"]),
        "CrossTen": f"{100 * cross['10']['delta']:+.1f}", "CrossThirty": f"{100 * cross['30']['delta']:+.1f}",
        "CrossFifty": f"{100 * cross['50']['delta']:+.1f}", "CrossFiftyLo": f"{100 * cross['50']['ci_low']:+.1f}", "CrossFiftyHi": f"{100 * cross['50']['ci_high']:+.1f}",
        "CrossHundred": f"{100 * cross['100']['delta']:+.1f}", "CrossFiveHundred": f"{100 * cross['500']['delta']:+.1f}",
        "OraclePairs": f"{x4['runs']['run4']['oracle_pairs_for_fixed_K30_coverage']:.1f}", "OracleCovAtThirty": pct(x4["runs"]["run4"]["oracle_coverage_at_30_pairs"]),
        "NeedOverHundred": pct(x4["runs"]["run4"]["share_needing_K_over_100"]), "NeedOverFiveHundred": pct(x4["runs"]["run4"]["share_needing_K_over_500"]),
        "DevRecallMin": f"{min(r['dev_shortlist_recall_K30'] for r in dev):.2f}", "DevRecallMax": f"{max(r['dev_shortlist_recall_K30'] for r in dev):.2f}",
        "BenchRecallMin": f"{min(r['bench_shortlist_recall_K30'] for r in dev):.3f}", "BenchRecallMax": f"{max(r['bench_shortlist_recall_K30'] for r in dev):.3f}",
        "DevSignFlips": str(sum(not r["sign_agrees"] for r in dev)), "DevConfigs": str(len(dev)),
    }
    lines = ["% generated by research/scripts/make_tables.py from research/results/X*; do not edit"]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in m.items()]
    (TEX / "numbers.tex").write_text("\n".join(lines) + "\n")
    print("wrote numbers.tex")


REP = REPO / "reports" / "results"


def _rep(name: str) -> dict:
    return json.loads((REP / name).read_text())


def _sysmap(run: dict) -> dict:
    return {m["system"]: m for m in run["metrics"]}


def t_config() -> None:
    import yaml

    base = yaml.safe_load((REPO / "configs" / "base.yaml").read_text())
    enc, tr, al = base["encoder"], base["training"], base["alignment"]
    summ = json.loads((REP / "training_summary_encoder_full_long.json").read_text())
    runs = [("Run 1", "benchmark.json"), ("Run 2", "benchmark_full96.json"), ("Run 3", "benchmark_full384.json"), ("Run 4", "benchmark_long384.json")]
    rows = [["input", "Da-TACOS HPCP, 12 pitch classes; encoder view area-pooled to " + str(enc["input_frames"]) + " frames"],
            ["encoder", f"TCN, {enc['n_blocks']} residual blocks, kernel {enc['kernel_size']}, dilations 1-{2 ** (enc['n_blocks'] - 1)}, "
                        f"{enc['channels']} channels, receptive field {summ['receptive_field_frames']} frames"],
            ["pooling and head", f"mean and max over time, MLP to {enc['embedding_dim']}-d, L2-normalised; {summ['n_parameters']:,} parameters"],
            ["training", f"supervised contrastive (temperature {tr['temperature']}), {tr['batch_wids']} works x 2 recordings per batch, AdamW lr {tr['lr']}, "
                         f"cosine schedule, crop {tr['crop_min_fraction']}-1.0, random pitch rotation, seed {base['seed']}"],
            ["Stage 1", "exact cosine search over all candidates, self excluded, top K = " + str(base["retrieval"]["shortlist_k"])],
            ["key handling", "one of 12 rotations, chosen by cosine of time-averaged chroma profiles"],
            ["alignment", f"cosine cost, subsequence DTW, steps {al['step_sizes']}, weights {al['step_weights']}, cost / path weight"],
            ["fusion", "alpha z(global) + (1 - alpha) z(alignment) within the shortlist"],
            ["hub correction", "alignment score minus lambda x mean score against 200 training-split probe queries"]]
    for lab, f in runs:
        lk = _rep(f)["locked_from_calibration"]
        hub = lk.get("hub_correction", {}).get("lambda", "-")
        rows.append([f"{lab} locked", f"checkpoint {Path(lk['checkpoint']).parent.name}, alignment frames {lk.get('n_frames', 96)}, alpha {lk['alpha']}, lambda {hub}"])
    write("t14_config", "System configuration, read from configs/base.yaml and the locked block of each benchmark result file",
          ["component", "setting"], rows, "configs/base.yaml, reports/results/benchmark*.json, training_summary_encoder_full_long.json", colspec=r"lp{0.74\linewidth}")


def t_runtime() -> None:
    runs = [("Run 1 (96 fr.)", "benchmark.json"), ("Run 2 (96 fr.)", "benchmark_full96.json"), ("Run 3 (384 fr.)", "benchmark_full384.json"), ("Run 4 (384 fr.)", "benchmark_long384.json")]
    rows = []
    pairs = 0
    for lab, f in runs:
        r = _rep(f)
        rt, pr = r["runtime"], r["protocol"]
        pairs = pr["queries"] * (pr["candidates"] - 1)
        k = r["locked_from_calibration"]["shortlist_k"]
        exh = f"{rt['alignment_only_s']:,.0f} s ({rt['alignment_only_s'] / 3600:.2f} h)" if "alignment_only_s" in rt else "not run (about 42 h, estimated)"
        rows.append([lab, f"{rt['embedding_s']:.0f} s", f"{rt['global_search_s']:.2f} s", f"{rt['rerank_s']:.0f} s ({rt['rerank_ms_per_query']:.1f} ms/query)",
                     f"{pr['queries'] * k:,} ({100 * k / (pr['candidates'] - 1):.2f}%)", exh, f"{rt['hub_reference_s']:.0f} s" if "hub_reference_s" in rt else "-"])
    write("t15_runtime", f"Measured runtime on the benchmark ({pairs:,} query-candidate pairs); exhaustive alignment is alignment-only time; run 2 reused the run-1 alignment matrix",
          ["run", "embed 15,000 tracks", "exact search", "K = 30 rerank", "pairs aligned at K = 30", "exhaustive alignment", "hub probe reference"],
          rows, "reports/results/benchmark*.json runtime blocks")


def numbers_paper() -> None:
    """Macros for the paper's prose that come from frozen runs, development files and the P1/P2 analyses."""
    r = {n: _rep(f) for n, f in (("one", "benchmark.json"), ("two", "benchmark_full96.json"), ("three", "benchmark_full384.json"), ("four", "benchmark_long384.json"))}
    s = {n: _sysmap(v) for n, v in r.items()}
    d96, d384, dlong = _rep("hybrid_dev.json"), _rep("hybrid_dev_n384.json"), _rep("hybrid_dev_long384.json")
    hd = _rep("hubness_dev.json")
    hc96, hc384 = _rep("hubness_correction.json"), _rep("hubness_correction_n384.json")
    tr = {n: json.loads((REP / f"training_summary_{n}.json").read_text()) for n in ("sweep_base", "encoder_full_train", "encoder_full_long")}
    import csv as _csv
    import numpy as _np
    hist = [float(x["val_map"]) for x in _csv.DictReader(open(REP / "training_history_encoder_full_long.csv"))]
    last30, prev30 = _np.array(hist[-30:]), _np.array(hist[-60:-30])  # the last two 30-epoch windows (epochs 91-120, 121-150)
    slope = float(_np.polyfit(_np.arange(len(hist) - 29, len(hist) + 1), last30, 1)[0])
    p1 = load("P1_rank1_hub_concentration")
    p2 = load("P2_dev_vs_benchmark")
    rt1, rt4 = r["one"]["runtime"], r["four"]["runtime"]
    pairs = r["one"]["protocol"]["queries"] * (r["one"]["protocol"]["candidates"] - 1)
    mp = lambda run, sysname: f"{s[run][sysname]['MAP']:.3f}"  # noqa: E731
    dm = lambda d, sysname: f"{next(x['MAP'] for x in d['metrics'] if x['system'] == sysname):.3f}"  # noqa: E731
    m = {
        "RunOneStage": mp("one", "global_embedding"), "RunTwoStage": mp("two", "global_embedding"), "RunFourStage": mp("four", "global_embedding"),
        "RunOneHyb": mp("one", "hybrid_K30_alpha0.05"), "RunTwoHyb": mp("two", "hybrid_K30_alpha0.15"), "RunThreeHyb": mp("three", "hybrid_K30_alpha0.15"),
        "RunFourHyb": mp("four", "hybrid_K30_alpha0.10"), "RunTwoHub": mp("two", "hybrid_hubcorr_K30_alpha0.15"), "RunThreeHub": mp("three", "hybrid_hubcorr_K30_alpha0.15"),
        "RunFourHub": mp("four", "hybrid_hubcorr_K30_alpha0.10"), "ClassicalMap": mp("one", "classical_alignment"), "ClassicalHubMap": mp("two", "classical_alignment_hubcorr"),
        "RunOneRecall": f"{r['one']['shortlist_recall']:.3f}", "RunTwoRecall": f"{r['two']['shortlist_recall']:.3f}", "RunFourRecall": f"{r['four']['shortlist_recall']:.3f}",
        "ClassicalOverHybOne": f"{s['one']['classical_alignment']['MAP'] / s['one']['hybrid_K30_alpha0.05']['MAP']:.1f}",
        "GapPctFour": f"{100 * (1 - s['four']['hybrid_hubcorr_K30_alpha0.10']['MAP'] / s['two']['classical_alignment_hubcorr']['MAP']):.0f}",
        "RerankGainFour": f"{r['four']['bootstrap_vs_global']['hybrid_K30_alpha0.10 - global_embedding']['delta']:+.4f}",
        "RerankGainFourLo": f"{r['four']['bootstrap_vs_global']['hybrid_K30_alpha0.10 - global_embedding']['ci_low']:+.4f}",
        "RerankGainFourHi": f"{r['four']['bootstrap_vs_global']['hybrid_K30_alpha0.10 - global_embedding']['ci_high']:+.4f}",
        "DevClassicalLow": dm(d96, "classical_alignment"), "DevClassicalHigh": dm(d384, "classical_alignment"),
        "DevHybLow": dm(d96, "hybrid_K30_alpha0.05"), "DevHybHigh": dm(d384, "hybrid_K30_alpha0.00"),
        "DevLongStage": dm(dlong, "global_embedding"), "DevLongHyb": dm(dlong, "hybrid_K30_alpha0.10"),
        "DevRecallRunOne": f"{d96['shortlist_recall']:.2f}", "DevRecallLong": f"{dlong['shortlist_recall']:.2f}",
        "ValSmall": f"{tr['sweep_base']['best_val_map']:.3f}", "ValFull": f"{tr['encoder_full_train']['best_val_map']:.3f}",
        "ValLong": f"{tr['encoder_full_long']['best_val_map']:.3f}", "ValLongBestEpoch": str(tr["encoder_full_long"]["best_epoch"]),
        "ValLongSlope": f"{slope:+.5f}", "ValMeanNinetyOne": f"{prev30.mean():.3f}", "ValMeanOneTwentyOne": f"{last30.mean():.3f}",
        "Params": f"{tr['encoder_full_long']['n_parameters']:,}".replace(",", "{,}"), "ReceptiveField": str(tr["encoder_full_long"]["receptive_field_frames"]),
        "RhoClassical": f"{hd['classical']['spearman_dispersion_vs_top10_fp']:.2f}", "RhoHybrid": f"{hd['hybrid']['spearman_dispersion_vs_top10_fp']:.2f}",
        "WorstHubCount": str(hd["classical"]["max_top10_fp_count"]), "UniformHubCount": f"{hd['expected_top10_fp_count_if_uniform']:.1f}",
        "RhoProbeLow": f"{hc96['dev_reference_vs_dispersion_spearman']:.2f}", "RhoProbeHigh": f"{hc384['dev_reference_vs_dispersion_spearman']:.2f}",
        "LambdaLow": str(hc96["locked"]["lambda"]), "LambdaHigh": str(hc384["locked"]["lambda"]),
        "EmbedSeconds": f"{rt4['embedding_s']:.0f}", "SearchSeconds": f"{rt4['global_search_s']:.2f}",
        "RerankSecondsLow": f"{rt1['rerank_s']:.0f}", "RerankSecondsHigh": f"{rt4['rerank_s']:.0f}",
        "RerankMsLow": f"{rt1['rerank_ms_per_query']:.1f}", "RerankMsHigh": f"{rt4['rerank_ms_per_query']:.0f}",
        "ExhaustiveSeconds": f"{rt1['alignment_only_s']:,.0f}".replace(",", "{,}"), "ExhaustiveHours": f"{rt1['alignment_only_s'] / 3600:.2f}",
        "ExhaustiveMsPerPair": f"{rt1['alignment_only_ms_per_pair']:.4f}", "HubProbeSecondsLow": f"{r['two']['runtime']['hub_reference_s']:.0f}",
        "HubProbeSecondsHigh": f"{rt4['hub_reference_s']:.0f}",
        "DevQueries": str(d96["protocol"]["n_queries"]), "DevCandidates": str(d96["protocol"]["n_candidates"] - 1),
        "DevShortlistShare": f"{100 * 30 / (d96['protocol']['n_candidates'] - 1):.0f}", "TotalPairs": f"{pairs / 1e8:.2f}", "ShortlistPct": f"{100 * 30 / (r['one']['protocol']['candidates'] - 1):.1f}",
    }
    x5 = load("X5_paired_ablations_benchmark")
    if x5:
        res = next(v for k, v in x5["comparisons"].items() if k.startswith("resolution") and "hub" not in k)
        d = res.get("delta_AP", res)
        m.update({"ResGain": f"{d['delta']:+.4f}", "ResGainLo": f"{d['ci_low']:+.4f}", "ResGainHi": f"{d['ci_high']:+.4f}"})
    if p1:
        for k, name in ((30, "Thirty"), (500, "FiveHundred")):
            for sname, tag in (("hyb", "Unc"), ("hub", "Cor")):
                e = p1["systems"][f"K{k}/{sname}"]
                m[f"POne{tag}{name}TopDecile"] = f"{100 * e['share_top_10pct']:.1f}"
                m[f"POne{tag}{name}BottomHalf"] = f"{100 * sum(e['share_by_reference_decile'][:5]):.1f}"
                m[f"POne{tag}{name}N"] = f"{e['n_rank1_false_positives_in_covered_queries']:,}".replace(",", "{,}")
        m["POneKoccRho"] = f"{p1['spearman_reference_vs_stage1_kocc10']:.2f}"
    if p2:
        m["PTwoSignFlips"] = str(sum(c["point_estimates_disagree_in_sign"] for c in p2["comparisons"]))
        m["PTwoDevInconclusive"] = str(sum(c["dev_interval_includes_zero"] for c in p2["comparisons"]))
        m["PTwoBenchDecisive"] = str(sum(c["benchmark_interval_excludes_zero"] for c in p2["comparisons"]))
        m["PTwoN"] = str(len(p2["comparisons"]))
        for i, c in enumerate(p2["comparisons"], 1):
            for side in ("dev", "benchmark"):
                tag = f"PTwo{chr(ord('A') + i - 1)}{'Dev' if side == 'dev' else 'Bench'}"
                m[tag] = f"{c[side]['delta']:+.3f}"
                m[tag + "Lo"] = f"{c[side]['ci_low']:+.3f}"
                m[tag + "Hi"] = f"{c[side]['ci_high']:+.3f}"
    lines = ["% generated by research/scripts/make_tables.py from reports/results/ and research/results/P*; do not edit"]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in m.items()]
    (TEX / "numbers_paper.tex").write_text("\n".join(lines) + "\n")
    print("wrote numbers_paper.tex")


def main() -> int:
    MD.mkdir(parents=True, exist_ok=True)
    TEX.mkdir(parents=True, exist_ok=True)
    for fn in (t1_protocol, t2_baselines, t3_ablations, t5_failures, t6_coverage, t_local, t_local_more, t_a2, t_config, t_runtime, numbers, numbers_local, numbers_paper):
        fn()
    (MD / "MISSING.txt").write_text("\n".join(sorted(set(MISSING))) + ("\n" if MISSING else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
