/**
 * Numeric data decoded from committed figures (reports/figures/*.png).
 *
 * Generated by web/scripts/extract_figures.py. The raw Da-TACOS HPCP features are
 * CC BY-NC-SA and never committed, so the site works from the figures instead:
 * colour maps are inverted back to a colour-scale position in [0, 1]. These values are
 * RELATIVE and quantised (256 levels, per-panel scale). Every visual built on them says so.
 *
 * Validation, run while building this site:
 *   - recomputing the 12 profile-rotation cosines from the decoded HPCP gives the same
 *     best shift as calibration_rotation_scores.png for all four pairs;
 *   - rerunning subsequence DTW on the decoded cost matrices gives paths within
 *     about 2-4 frames (mean, of 96) of the published red paths.
 */
import raw from './generated/figures.json'

interface Packed {
  shape: [number, number]
  /** uint8 colour-scale positions (LUT index), row-major, base64 */
  u8: string
}

/** Unpack a base64 uint8 matrix into rows of values in [0, 1]. */
function unpack(p: Packed): number[][] {
  const bin = atob(p.u8)
  const [rows, cols] = p.shape
  return Array.from({ length: rows }, (_, r) => Array.from({ length: cols }, (_, c) => bin.charCodeAt(r * cols + c) / 255))
}

export interface HPCPPanel {
  source: string
  /** (12, 96) colour-scale positions, pitch class x frame */
  values: number[][]
}
export interface RotationPair {
  kind: 'cover' | 'non-cover'
  query: string
  candidate: string
  best_shift: number
  /** bar heights read from the figure (profile cosine, 0..1 axis) */
  profile_cosine: number[]
}
export interface AlignmentPanel {
  source: string
  kind: 'cover' | 'non-cover'
  shift: number
  /** normalised path cost printed in the figure title */
  published_cost: number
  /** (96, 96) cosine distance, colour-scale position (0 = figure p1, 1 = figure p99) */
  cost: number[][]
  /** [query frame, candidate frame] read from the red line */
  published_path: [number, number][]
}

interface FiguresFile {
  hpcp: Record<string, { source: string; values: Packed }>
  profile: { source: string; pid: string; raw_frames: number; raw_pixels: Packed; preprocessed: Packed }
  rotations: { source: string; pairs: RotationPair[] }
  alignments: Record<string, Omit<AlignmentPanel, 'cost'> & { cost: Packed }>
}

const file = raw as unknown as FiguresFile

const mapValues = <A, B>(o: Record<string, A>, f: (a: A) => B): Record<string, B> =>
  Object.fromEntries(Object.entries(o).map(([k, v]) => [k, f(v)]))

export const hpcp: Record<string, HPCPPanel> = mapValues(file.hpcp, (h) => ({ source: h.source, values: unpack(h.values) }))
export const profileFigure = {
  ...file.profile,
  raw_pixels: unpack(file.profile.raw_pixels),
  preprocessed: unpack(file.profile.preprocessed),
}
export const rotationPairs = file.rotations.pairs
export const rotationSource = file.rotations.source
export const alignments: Record<string, AlignmentPanel> = mapValues(file.alignments, (a) => ({ ...a, cost: unpack(a.cost) }))
